package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * AdvertisementAction generated by hbm2java
 */
public class AdvertisementAction implements java.io.Serializable {

	private Integer id;
	private String sellerCode;
	private String campaignName;
	private String adGroupName;
	private String keyword;
	private Date startDate;
	private Date endDate;
	private String proposedAction;
	private String realAction;
	private String result;

	public AdvertisementAction() {
	}

	public AdvertisementAction(String sellerCode, String campaignName, String adGroupName, String keyword,
			Date startDate, Date endDate, String proposedAction, String realAction, String result) {
		this.sellerCode = sellerCode;
		this.campaignName = campaignName;
		this.adGroupName = adGroupName;
		this.keyword = keyword;
		this.startDate = startDate;
		this.endDate = endDate;
		this.proposedAction = proposedAction;
		this.realAction = realAction;
		this.result = result;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSellerCode() {
		return this.sellerCode;
	}

	public void setSellerCode(String sellerCode) {
		this.sellerCode = sellerCode;
	}

	public String getCampaignName() {
		return this.campaignName;
	}

	public void setCampaignName(String campaignName) {
		this.campaignName = campaignName;
	}

	public String getAdGroupName() {
		return this.adGroupName;
	}

	public void setAdGroupName(String adGroupName) {
		this.adGroupName = adGroupName;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getProposedAction() {
		return this.proposedAction;
	}

	public void setProposedAction(String proposedAction) {
		this.proposedAction = proposedAction;
	}

	public String getRealAction() {
		return this.realAction;
	}

	public void setRealAction(String realAction) {
		this.realAction = realAction;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
