package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * GeneralExceptionRecord generated by hbm2java
 */
public class GeneralExceptionRecord implements java.io.Serializable {

	private String exceptionId;
	private String exceptionMessage;
	private String firstExceptionClass;
	private Integer firstExceptionClassLine;
	private Date tstamp;
	private String merchant;

	public GeneralExceptionRecord() {
	}

	public GeneralExceptionRecord(String exceptionId) {
		this.exceptionId = exceptionId;
	}

	public GeneralExceptionRecord(String exceptionId, String exceptionMessage, String firstExceptionClass,
			Integer firstExceptionClassLine, Date tstamp, String merchant) {
		this.exceptionId = exceptionId;
		this.exceptionMessage = exceptionMessage;
		this.firstExceptionClass = firstExceptionClass;
		this.firstExceptionClassLine = firstExceptionClassLine;
		this.tstamp = tstamp;
		this.merchant = merchant;
	}

	public String getExceptionId() {
		return this.exceptionId;
	}

	public void setExceptionId(String exceptionId) {
		this.exceptionId = exceptionId;
	}

	public String getExceptionMessage() {
		return this.exceptionMessage;
	}

	public void setExceptionMessage(String exceptionMessage) {
		this.exceptionMessage = exceptionMessage;
	}

	public String getFirstExceptionClass() {
		return this.firstExceptionClass;
	}

	public void setFirstExceptionClass(String firstExceptionClass) {
		this.firstExceptionClass = firstExceptionClass;
	}

	public Integer getFirstExceptionClassLine() {
		return this.firstExceptionClassLine;
	}

	public void setFirstExceptionClassLine(Integer firstExceptionClassLine) {
		this.firstExceptionClassLine = firstExceptionClassLine;
	}

	public Date getTstamp() {
		return this.tstamp;
	}

	public void setTstamp(Date tstamp) {
		this.tstamp = tstamp;
	}

	public String getMerchant() {
		return this.merchant;
	}

	public void setMerchant(String merchant) {
		this.merchant = merchant;
	}

}
