package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

/**
 * MerchantInboundAddress generated by hbm2java
 */
public class MerchantInboundAddress implements java.io.Serializable {

	private Integer id;
	private MerchantAccount merchantAccount;
	private String name;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String countryCode;

	public MerchantInboundAddress() {
	}

	public MerchantInboundAddress(MerchantAccount merchantAccount, String name, String addressLine1,
			String addressLine2, String city, String countryCode) {
		this.merchantAccount = merchantAccount;
		this.name = name;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.countryCode = countryCode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MerchantAccount getMerchantAccount() {
		return this.merchantAccount;
	}

	public void setMerchantAccount(MerchantAccount merchantAccount) {
		this.merchantAccount = merchantAccount;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

}
