package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

/**
 * MerchantMfnAddress generated by hbm2java
 */
public class MerchantMfnAddress implements java.io.Serializable {

	private Integer id;
	private MerchantAccount merchantAccount;
	private String name;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String email;
	private String countryCode;
	private String postalCode;
	private String phone;
	private String stateProvinceCode;

	public MerchantMfnAddress() {
	}

	public MerchantMfnAddress(MerchantAccount merchantAccount, String name, String addressLine1, String addressLine2,
			String city, String email, String countryCode, String postalCode, String phone, String stateProvinceCode) {
		this.merchantAccount = merchantAccount;
		this.name = name;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.email = email;
		this.countryCode = countryCode;
		this.postalCode = postalCode;
		this.phone = phone;
		this.stateProvinceCode = stateProvinceCode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MerchantAccount getMerchantAccount() {
		return this.merchantAccount;
	}

	public void setMerchantAccount(MerchantAccount merchantAccount) {
		this.merchantAccount = merchantAccount;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getStateProvinceCode() {
		return this.stateProvinceCode;
	}

	public void setStateProvinceCode(String stateProvinceCode) {
		this.stateProvinceCode = stateProvinceCode;
	}

}
