package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ProductCategories generated by hbm2java
 */
public class ProductCategories implements java.io.Serializable {

	private String productCategoryId;
	private ProductCategories productCategories;
	private String productCategoryName;
	private Set productCategorieses = new HashSet(0);
	private Set productSalesRanks = new HashSet(0);
	private Set productAsinCategoryDatas = new HashSet(0);

	public ProductCategories() {
	}

	public ProductCategories(String productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	public ProductCategories(String productCategoryId, ProductCategories productCategories, String productCategoryName,
			Set productCategorieses, Set productSalesRanks, Set productAsinCategoryDatas) {
		this.productCategoryId = productCategoryId;
		this.productCategories = productCategories;
		this.productCategoryName = productCategoryName;
		this.productCategorieses = productCategorieses;
		this.productSalesRanks = productSalesRanks;
		this.productAsinCategoryDatas = productAsinCategoryDatas;
	}

	public String getProductCategoryId() {
		return this.productCategoryId;
	}

	public void setProductCategoryId(String productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	public ProductCategories getProductCategories() {
		return this.productCategories;
	}

	public void setProductCategories(ProductCategories productCategories) {
		this.productCategories = productCategories;
	}

	public String getProductCategoryName() {
		return this.productCategoryName;
	}

	public void setProductCategoryName(String productCategoryName) {
		this.productCategoryName = productCategoryName;
	}

	public Set getProductCategorieses() {
		return this.productCategorieses;
	}

	public void setProductCategorieses(Set productCategorieses) {
		this.productCategorieses = productCategorieses;
	}

	public Set getProductSalesRanks() {
		return this.productSalesRanks;
	}

	public void setProductSalesRanks(Set productSalesRanks) {
		this.productSalesRanks = productSalesRanks;
	}

	public Set getProductAsinCategoryDatas() {
		return this.productAsinCategoryDatas;
	}

	public void setProductAsinCategoryDatas(Set productAsinCategoryDatas) {
		this.productAsinCategoryDatas = productAsinCategoryDatas;
	}

}
