package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * ProductOfferDetailData generated by hbm2java
 */
public class ProductOfferDetailData implements java.io.Serializable {

	private int id;
	private ProductLowestPricedOffersData productLowestPricedOffersData;
	private String subCondition;
	private Float sellerFeedbackRatingPositiveRate;
	private Integer sellerFeedbackRatingCount;
	private Integer shippingTimeMinHours;
	private Integer shippingTimeMaxHours;
	private Date shippingTimeAvailableDate;
	private String shippingTimeAvailabilityType;
	private String listingPriceCurrency;
	private BigDecimal listingPriceAmount;
	private String shippingCurrency;
	private BigDecimal shippingAmount;
	private String shipsFromState;
	private String shipsFromCountry;
	private String isFulfilledByAmazon;
	private String isBuyBoxWinner;
	private String isFeaturedMerchant;

	public ProductOfferDetailData() {
	}

	public ProductOfferDetailData(int id) {
		this.id = id;
	}

	public ProductOfferDetailData(int id, ProductLowestPricedOffersData productLowestPricedOffersData,
			String subCondition, Float sellerFeedbackRatingPositiveRate, Integer sellerFeedbackRatingCount,
			Integer shippingTimeMinHours, Integer shippingTimeMaxHours, Date shippingTimeAvailableDate,
			String shippingTimeAvailabilityType, String listingPriceCurrency, BigDecimal listingPriceAmount,
			String shippingCurrency, BigDecimal shippingAmount, String shipsFromState, String shipsFromCountry,
			String isFulfilledByAmazon, String isBuyBoxWinner, String isFeaturedMerchant) {
		this.id = id;
		this.productLowestPricedOffersData = productLowestPricedOffersData;
		this.subCondition = subCondition;
		this.sellerFeedbackRatingPositiveRate = sellerFeedbackRatingPositiveRate;
		this.sellerFeedbackRatingCount = sellerFeedbackRatingCount;
		this.shippingTimeMinHours = shippingTimeMinHours;
		this.shippingTimeMaxHours = shippingTimeMaxHours;
		this.shippingTimeAvailableDate = shippingTimeAvailableDate;
		this.shippingTimeAvailabilityType = shippingTimeAvailabilityType;
		this.listingPriceCurrency = listingPriceCurrency;
		this.listingPriceAmount = listingPriceAmount;
		this.shippingCurrency = shippingCurrency;
		this.shippingAmount = shippingAmount;
		this.shipsFromState = shipsFromState;
		this.shipsFromCountry = shipsFromCountry;
		this.isFulfilledByAmazon = isFulfilledByAmazon;
		this.isBuyBoxWinner = isBuyBoxWinner;
		this.isFeaturedMerchant = isFeaturedMerchant;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ProductLowestPricedOffersData getProductLowestPricedOffersData() {
		return this.productLowestPricedOffersData;
	}

	public void setProductLowestPricedOffersData(ProductLowestPricedOffersData productLowestPricedOffersData) {
		this.productLowestPricedOffersData = productLowestPricedOffersData;
	}

	public String getSubCondition() {
		return this.subCondition;
	}

	public void setSubCondition(String subCondition) {
		this.subCondition = subCondition;
	}

	public Float getSellerFeedbackRatingPositiveRate() {
		return this.sellerFeedbackRatingPositiveRate;
	}

	public void setSellerFeedbackRatingPositiveRate(Float sellerFeedbackRatingPositiveRate) {
		this.sellerFeedbackRatingPositiveRate = sellerFeedbackRatingPositiveRate;
	}

	public Integer getSellerFeedbackRatingCount() {
		return this.sellerFeedbackRatingCount;
	}

	public void setSellerFeedbackRatingCount(Integer sellerFeedbackRatingCount) {
		this.sellerFeedbackRatingCount = sellerFeedbackRatingCount;
	}

	public Integer getShippingTimeMinHours() {
		return this.shippingTimeMinHours;
	}

	public void setShippingTimeMinHours(Integer shippingTimeMinHours) {
		this.shippingTimeMinHours = shippingTimeMinHours;
	}

	public Integer getShippingTimeMaxHours() {
		return this.shippingTimeMaxHours;
	}

	public void setShippingTimeMaxHours(Integer shippingTimeMaxHours) {
		this.shippingTimeMaxHours = shippingTimeMaxHours;
	}

	public Date getShippingTimeAvailableDate() {
		return this.shippingTimeAvailableDate;
	}

	public void setShippingTimeAvailableDate(Date shippingTimeAvailableDate) {
		this.shippingTimeAvailableDate = shippingTimeAvailableDate;
	}

	public String getShippingTimeAvailabilityType() {
		return this.shippingTimeAvailabilityType;
	}

	public void setShippingTimeAvailabilityType(String shippingTimeAvailabilityType) {
		this.shippingTimeAvailabilityType = shippingTimeAvailabilityType;
	}

	public String getListingPriceCurrency() {
		return this.listingPriceCurrency;
	}

	public void setListingPriceCurrency(String listingPriceCurrency) {
		this.listingPriceCurrency = listingPriceCurrency;
	}

	public BigDecimal getListingPriceAmount() {
		return this.listingPriceAmount;
	}

	public void setListingPriceAmount(BigDecimal listingPriceAmount) {
		this.listingPriceAmount = listingPriceAmount;
	}

	public String getShippingCurrency() {
		return this.shippingCurrency;
	}

	public void setShippingCurrency(String shippingCurrency) {
		this.shippingCurrency = shippingCurrency;
	}

	public BigDecimal getShippingAmount() {
		return this.shippingAmount;
	}

	public void setShippingAmount(BigDecimal shippingAmount) {
		this.shippingAmount = shippingAmount;
	}

	public String getShipsFromState() {
		return this.shipsFromState;
	}

	public void setShipsFromState(String shipsFromState) {
		this.shipsFromState = shipsFromState;
	}

	public String getShipsFromCountry() {
		return this.shipsFromCountry;
	}

	public void setShipsFromCountry(String shipsFromCountry) {
		this.shipsFromCountry = shipsFromCountry;
	}

	public String getIsFulfilledByAmazon() {
		return this.isFulfilledByAmazon;
	}

	public void setIsFulfilledByAmazon(String isFulfilledByAmazon) {
		this.isFulfilledByAmazon = isFulfilledByAmazon;
	}

	public String getIsBuyBoxWinner() {
		return this.isBuyBoxWinner;
	}

	public void setIsBuyBoxWinner(String isBuyBoxWinner) {
		this.isBuyBoxWinner = isBuyBoxWinner;
	}

	public String getIsFeaturedMerchant() {
		return this.isFeaturedMerchant;
	}

	public void setIsFeaturedMerchant(String isFeaturedMerchant) {
		this.isFeaturedMerchant = isFeaturedMerchant;
	}

}
