package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * ProductOfferListing generated by hbm2java
 */
public class ProductOfferListing implements java.io.Serializable {

	private int id;
	private ProductCompetitivePricingData productCompetitivePricingData;
	private String buyingPriceLandedCurrency;
	private BigDecimal buyingPriceLandedAmount;
	private String buyingPriceListingCurrency;
	private BigDecimal buyingPriceListingAmount;
	private String buyingPriceShippingCurrency;
	private BigDecimal buyingPriceShippingAmount;
	private String fulfillmentChannel;
	private String itemCondition;
	private String itemSubCondition;
	private String sellerId;
	private String sellerSku;
	private String regularPriceCurrency;
	private BigDecimal regularPriceAmount;

	public ProductOfferListing() {
	}

	public ProductOfferListing(int id) {
		this.id = id;
	}

	public ProductOfferListing(int id, ProductCompetitivePricingData productCompetitivePricingData,
			String buyingPriceLandedCurrency, BigDecimal buyingPriceLandedAmount, String buyingPriceListingCurrency,
			BigDecimal buyingPriceListingAmount, String buyingPriceShippingCurrency,
			BigDecimal buyingPriceShippingAmount, String fulfillmentChannel, String itemCondition,
			String itemSubCondition, String sellerId, String sellerSku, String regularPriceCurrency,
			BigDecimal regularPriceAmount) {
		this.id = id;
		this.productCompetitivePricingData = productCompetitivePricingData;
		this.buyingPriceLandedCurrency = buyingPriceLandedCurrency;
		this.buyingPriceLandedAmount = buyingPriceLandedAmount;
		this.buyingPriceListingCurrency = buyingPriceListingCurrency;
		this.buyingPriceListingAmount = buyingPriceListingAmount;
		this.buyingPriceShippingCurrency = buyingPriceShippingCurrency;
		this.buyingPriceShippingAmount = buyingPriceShippingAmount;
		this.fulfillmentChannel = fulfillmentChannel;
		this.itemCondition = itemCondition;
		this.itemSubCondition = itemSubCondition;
		this.sellerId = sellerId;
		this.sellerSku = sellerSku;
		this.regularPriceCurrency = regularPriceCurrency;
		this.regularPriceAmount = regularPriceAmount;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ProductCompetitivePricingData getProductCompetitivePricingData() {
		return this.productCompetitivePricingData;
	}

	public void setProductCompetitivePricingData(ProductCompetitivePricingData productCompetitivePricingData) {
		this.productCompetitivePricingData = productCompetitivePricingData;
	}

	public String getBuyingPriceLandedCurrency() {
		return this.buyingPriceLandedCurrency;
	}

	public void setBuyingPriceLandedCurrency(String buyingPriceLandedCurrency) {
		this.buyingPriceLandedCurrency = buyingPriceLandedCurrency;
	}

	public BigDecimal getBuyingPriceLandedAmount() {
		return this.buyingPriceLandedAmount;
	}

	public void setBuyingPriceLandedAmount(BigDecimal buyingPriceLandedAmount) {
		this.buyingPriceLandedAmount = buyingPriceLandedAmount;
	}

	public String getBuyingPriceListingCurrency() {
		return this.buyingPriceListingCurrency;
	}

	public void setBuyingPriceListingCurrency(String buyingPriceListingCurrency) {
		this.buyingPriceListingCurrency = buyingPriceListingCurrency;
	}

	public BigDecimal getBuyingPriceListingAmount() {
		return this.buyingPriceListingAmount;
	}

	public void setBuyingPriceListingAmount(BigDecimal buyingPriceListingAmount) {
		this.buyingPriceListingAmount = buyingPriceListingAmount;
	}

	public String getBuyingPriceShippingCurrency() {
		return this.buyingPriceShippingCurrency;
	}

	public void setBuyingPriceShippingCurrency(String buyingPriceShippingCurrency) {
		this.buyingPriceShippingCurrency = buyingPriceShippingCurrency;
	}

	public BigDecimal getBuyingPriceShippingAmount() {
		return this.buyingPriceShippingAmount;
	}

	public void setBuyingPriceShippingAmount(BigDecimal buyingPriceShippingAmount) {
		this.buyingPriceShippingAmount = buyingPriceShippingAmount;
	}

	public String getFulfillmentChannel() {
		return this.fulfillmentChannel;
	}

	public void setFulfillmentChannel(String fulfillmentChannel) {
		this.fulfillmentChannel = fulfillmentChannel;
	}

	public String getItemCondition() {
		return this.itemCondition;
	}

	public void setItemCondition(String itemCondition) {
		this.itemCondition = itemCondition;
	}

	public String getItemSubCondition() {
		return this.itemSubCondition;
	}

	public void setItemSubCondition(String itemSubCondition) {
		this.itemSubCondition = itemSubCondition;
	}

	public String getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(String sellerId) {
		this.sellerId = sellerId;
	}

	public String getSellerSku() {
		return this.sellerSku;
	}

	public void setSellerSku(String sellerSku) {
		this.sellerSku = sellerSku;
	}

	public String getRegularPriceCurrency() {
		return this.regularPriceCurrency;
	}

	public void setRegularPriceCurrency(String regularPriceCurrency) {
		this.regularPriceCurrency = regularPriceCurrency;
	}

	public BigDecimal getRegularPriceAmount() {
		return this.regularPriceAmount;
	}

	public void setRegularPriceAmount(BigDecimal regularPriceAmount) {
		this.regularPriceAmount = regularPriceAmount;
	}

}
