package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * ProductCompetitivePrice generated by hbm2java
 */
public class ProductCompetitivePrice implements java.io.Serializable {

	private Integer id;
	private ProductCompetitivePricingData productCompetitivePricingData;
	private String competitivePriceId;
	private String conditions;
	private String subcondition;
	private String priceLandedCurrency;
	private BigDecimal priceLandedAmount;
	private String priceListingCurrency;
	private BigDecimal priceListingAmount;
	private String priceShippingCurrency;
	private BigDecimal priceShippingAmount;

	public ProductCompetitivePrice() {
	}

	public ProductCompetitivePrice(ProductCompetitivePricingData productCompetitivePricingData,
			String competitivePriceId, String conditions, String subcondition, String priceLandedCurrency,
			BigDecimal priceLandedAmount, String priceListingCurrency, BigDecimal priceListingAmount,
			String priceShippingCurrency, BigDecimal priceShippingAmount) {
		this.productCompetitivePricingData = productCompetitivePricingData;
		this.competitivePriceId = competitivePriceId;
		this.conditions = conditions;
		this.subcondition = subcondition;
		this.priceLandedCurrency = priceLandedCurrency;
		this.priceLandedAmount = priceLandedAmount;
		this.priceListingCurrency = priceListingCurrency;
		this.priceListingAmount = priceListingAmount;
		this.priceShippingCurrency = priceShippingCurrency;
		this.priceShippingAmount = priceShippingAmount;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ProductCompetitivePricingData getProductCompetitivePricingData() {
		return this.productCompetitivePricingData;
	}

	public void setProductCompetitivePricingData(ProductCompetitivePricingData productCompetitivePricingData) {
		this.productCompetitivePricingData = productCompetitivePricingData;
	}

	public String getCompetitivePriceId() {
		return this.competitivePriceId;
	}

	public void setCompetitivePriceId(String competitivePriceId) {
		this.competitivePriceId = competitivePriceId;
	}

	public String getConditions() {
		return this.conditions;
	}

	public void setConditions(String conditions) {
		this.conditions = conditions;
	}

	public String getSubcondition() {
		return this.subcondition;
	}

	public void setSubcondition(String subcondition) {
		this.subcondition = subcondition;
	}

	public String getPriceLandedCurrency() {
		return this.priceLandedCurrency;
	}

	public void setPriceLandedCurrency(String priceLandedCurrency) {
		this.priceLandedCurrency = priceLandedCurrency;
	}

	public BigDecimal getPriceLandedAmount() {
		return this.priceLandedAmount;
	}

	public void setPriceLandedAmount(BigDecimal priceLandedAmount) {
		this.priceLandedAmount = priceLandedAmount;
	}

	public String getPriceListingCurrency() {
		return this.priceListingCurrency;
	}

	public void setPriceListingCurrency(String priceListingCurrency) {
		this.priceListingCurrency = priceListingCurrency;
	}

	public BigDecimal getPriceListingAmount() {
		return this.priceListingAmount;
	}

	public void setPriceListingAmount(BigDecimal priceListingAmount) {
		this.priceListingAmount = priceListingAmount;
	}

	public String getPriceShippingCurrency() {
		return this.priceShippingCurrency;
	}

	public void setPriceShippingCurrency(String priceShippingCurrency) {
		this.priceShippingCurrency = priceShippingCurrency;
	}

	public BigDecimal getPriceShippingAmount() {
		return this.priceShippingAmount;
	}

	public void setPriceShippingAmount(BigDecimal priceShippingAmount) {
		this.priceShippingAmount = priceShippingAmount;
	}

}
