package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductLowestPricedOffersData generated by hbm2java
 */
public class ProductLowestPricedOffersData implements java.io.Serializable {

	private int id;
	private GeneralResponseRecord generalResponseRecord;
	private String marketplaceId;
	private String asin;
	private String itemCondition;
	private String status;
	private Date tstamp;
	private String lowestOfferMarketplaceId;
	private String lowestOfferAsin;
	private String lowestOfferItemCondition;
	private Date lowestOfferTimeOfOfferChange;
	private String listPriceCurrency;
	private BigDecimal listPriceAmount;
	private String suggestedLowerPricePlusShippingCurrency;
	private BigDecimal suggestedLowerPricePlusShippingAmount;
	private Set productOfferCountDatas = new HashSet(0);
	private Set productOfferPriceDatas = new HashSet(0);
	private Set productOfferDetailDatas = new HashSet(0);

	public ProductLowestPricedOffersData() {
	}

	public ProductLowestPricedOffersData(int id) {
		this.id = id;
	}

	public ProductLowestPricedOffersData(int id, GeneralResponseRecord generalResponseRecord, String marketplaceId,
			String asin, String itemCondition, String status, Date tstamp, String lowestOfferMarketplaceId,
			String lowestOfferAsin, String lowestOfferItemCondition, Date lowestOfferTimeOfOfferChange,
			String listPriceCurrency, BigDecimal listPriceAmount, String suggestedLowerPricePlusShippingCurrency,
			BigDecimal suggestedLowerPricePlusShippingAmount, Set productOfferCountDatas, Set productOfferPriceDatas,
			Set productOfferDetailDatas) {
		this.id = id;
		this.generalResponseRecord = generalResponseRecord;
		this.marketplaceId = marketplaceId;
		this.asin = asin;
		this.itemCondition = itemCondition;
		this.status = status;
		this.tstamp = tstamp;
		this.lowestOfferMarketplaceId = lowestOfferMarketplaceId;
		this.lowestOfferAsin = lowestOfferAsin;
		this.lowestOfferItemCondition = lowestOfferItemCondition;
		this.lowestOfferTimeOfOfferChange = lowestOfferTimeOfOfferChange;
		this.listPriceCurrency = listPriceCurrency;
		this.listPriceAmount = listPriceAmount;
		this.suggestedLowerPricePlusShippingCurrency = suggestedLowerPricePlusShippingCurrency;
		this.suggestedLowerPricePlusShippingAmount = suggestedLowerPricePlusShippingAmount;
		this.productOfferCountDatas = productOfferCountDatas;
		this.productOfferPriceDatas = productOfferPriceDatas;
		this.productOfferDetailDatas = productOfferDetailDatas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public GeneralResponseRecord getGeneralResponseRecord() {
		return this.generalResponseRecord;
	}

	public void setGeneralResponseRecord(GeneralResponseRecord generalResponseRecord) {
		this.generalResponseRecord = generalResponseRecord;
	}

	public String getMarketplaceId() {
		return this.marketplaceId;
	}

	public void setMarketplaceId(String marketplaceId) {
		this.marketplaceId = marketplaceId;
	}

	public String getAsin() {
		return this.asin;
	}

	public void setAsin(String asin) {
		this.asin = asin;
	}

	public String getItemCondition() {
		return this.itemCondition;
	}

	public void setItemCondition(String itemCondition) {
		this.itemCondition = itemCondition;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getTstamp() {
		return this.tstamp;
	}

	public void setTstamp(Date tstamp) {
		this.tstamp = tstamp;
	}

	public String getLowestOfferMarketplaceId() {
		return this.lowestOfferMarketplaceId;
	}

	public void setLowestOfferMarketplaceId(String lowestOfferMarketplaceId) {
		this.lowestOfferMarketplaceId = lowestOfferMarketplaceId;
	}

	public String getLowestOfferAsin() {
		return this.lowestOfferAsin;
	}

	public void setLowestOfferAsin(String lowestOfferAsin) {
		this.lowestOfferAsin = lowestOfferAsin;
	}

	public String getLowestOfferItemCondition() {
		return this.lowestOfferItemCondition;
	}

	public void setLowestOfferItemCondition(String lowestOfferItemCondition) {
		this.lowestOfferItemCondition = lowestOfferItemCondition;
	}

	public Date getLowestOfferTimeOfOfferChange() {
		return this.lowestOfferTimeOfOfferChange;
	}

	public void setLowestOfferTimeOfOfferChange(Date lowestOfferTimeOfOfferChange) {
		this.lowestOfferTimeOfOfferChange = lowestOfferTimeOfOfferChange;
	}

	public String getListPriceCurrency() {
		return this.listPriceCurrency;
	}

	public void setListPriceCurrency(String listPriceCurrency) {
		this.listPriceCurrency = listPriceCurrency;
	}

	public BigDecimal getListPriceAmount() {
		return this.listPriceAmount;
	}

	public void setListPriceAmount(BigDecimal listPriceAmount) {
		this.listPriceAmount = listPriceAmount;
	}

	public String getSuggestedLowerPricePlusShippingCurrency() {
		return this.suggestedLowerPricePlusShippingCurrency;
	}

	public void setSuggestedLowerPricePlusShippingCurrency(String suggestedLowerPricePlusShippingCurrency) {
		this.suggestedLowerPricePlusShippingCurrency = suggestedLowerPricePlusShippingCurrency;
	}

	public BigDecimal getSuggestedLowerPricePlusShippingAmount() {
		return this.suggestedLowerPricePlusShippingAmount;
	}

	public void setSuggestedLowerPricePlusShippingAmount(BigDecimal suggestedLowerPricePlusShippingAmount) {
		this.suggestedLowerPricePlusShippingAmount = suggestedLowerPricePlusShippingAmount;
	}

	public Set getProductOfferCountDatas() {
		return this.productOfferCountDatas;
	}

	public void setProductOfferCountDatas(Set productOfferCountDatas) {
		this.productOfferCountDatas = productOfferCountDatas;
	}

	public Set getProductOfferPriceDatas() {
		return this.productOfferPriceDatas;
	}

	public void setProductOfferPriceDatas(Set productOfferPriceDatas) {
		this.productOfferPriceDatas = productOfferPriceDatas;
	}

	public Set getProductOfferDetailDatas() {
		return this.productOfferDetailDatas;
	}

	public void setProductOfferDetailDatas(Set productOfferDetailDatas) {
		this.productOfferDetailDatas = productOfferDetailDatas;
	}

}
