package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * ProductCompetitiveLowestPricedOffersData generated by hbm2java
 */
public class ProductCompetitiveLowestPricedOffersData implements java.io.Serializable {

	private int id;
	private ProductCompetitivePricingData productCompetitivePricingData;
	private String multipleOffersAtLowestPrice;
	private Integer sellerFeedbackCount;
	private Integer numberOfOfferListingsConsidered;
	private String priceLandedCurrency;
	private BigDecimal priceLandedAmount;
	private String priceListingCurrency;
	private BigDecimal priceListingAmount;
	private String priceShippingCurrency;
	private BigDecimal priceShippingAmount;
	private String fulfillmentChannel;
	private String itemCondition;
	private String itemSubcondition;
	private String sellerPositiveFeedbackRating;
	private String shipsDomestically;
	private String maxShippingTime;

	public ProductCompetitiveLowestPricedOffersData() {
	}

	public ProductCompetitiveLowestPricedOffersData(int id) {
		this.id = id;
	}

	public ProductCompetitiveLowestPricedOffersData(int id, ProductCompetitivePricingData productCompetitivePricingData,
			String multipleOffersAtLowestPrice, Integer sellerFeedbackCount, Integer numberOfOfferListingsConsidered,
			String priceLandedCurrency, BigDecimal priceLandedAmount, String priceListingCurrency,
			BigDecimal priceListingAmount, String priceShippingCurrency, BigDecimal priceShippingAmount,
			String fulfillmentChannel, String itemCondition, String itemSubcondition,
			String sellerPositiveFeedbackRating, String shipsDomestically, String maxShippingTime) {
		this.id = id;
		this.productCompetitivePricingData = productCompetitivePricingData;
		this.multipleOffersAtLowestPrice = multipleOffersAtLowestPrice;
		this.sellerFeedbackCount = sellerFeedbackCount;
		this.numberOfOfferListingsConsidered = numberOfOfferListingsConsidered;
		this.priceLandedCurrency = priceLandedCurrency;
		this.priceLandedAmount = priceLandedAmount;
		this.priceListingCurrency = priceListingCurrency;
		this.priceListingAmount = priceListingAmount;
		this.priceShippingCurrency = priceShippingCurrency;
		this.priceShippingAmount = priceShippingAmount;
		this.fulfillmentChannel = fulfillmentChannel;
		this.itemCondition = itemCondition;
		this.itemSubcondition = itemSubcondition;
		this.sellerPositiveFeedbackRating = sellerPositiveFeedbackRating;
		this.shipsDomestically = shipsDomestically;
		this.maxShippingTime = maxShippingTime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ProductCompetitivePricingData getProductCompetitivePricingData() {
		return this.productCompetitivePricingData;
	}

	public void setProductCompetitivePricingData(ProductCompetitivePricingData productCompetitivePricingData) {
		this.productCompetitivePricingData = productCompetitivePricingData;
	}

	public String getMultipleOffersAtLowestPrice() {
		return this.multipleOffersAtLowestPrice;
	}

	public void setMultipleOffersAtLowestPrice(String multipleOffersAtLowestPrice) {
		this.multipleOffersAtLowestPrice = multipleOffersAtLowestPrice;
	}

	public Integer getSellerFeedbackCount() {
		return this.sellerFeedbackCount;
	}

	public void setSellerFeedbackCount(Integer sellerFeedbackCount) {
		this.sellerFeedbackCount = sellerFeedbackCount;
	}

	public Integer getNumberOfOfferListingsConsidered() {
		return this.numberOfOfferListingsConsidered;
	}

	public void setNumberOfOfferListingsConsidered(Integer numberOfOfferListingsConsidered) {
		this.numberOfOfferListingsConsidered = numberOfOfferListingsConsidered;
	}

	public String getPriceLandedCurrency() {
		return this.priceLandedCurrency;
	}

	public void setPriceLandedCurrency(String priceLandedCurrency) {
		this.priceLandedCurrency = priceLandedCurrency;
	}

	public BigDecimal getPriceLandedAmount() {
		return this.priceLandedAmount;
	}

	public void setPriceLandedAmount(BigDecimal priceLandedAmount) {
		this.priceLandedAmount = priceLandedAmount;
	}

	public String getPriceListingCurrency() {
		return this.priceListingCurrency;
	}

	public void setPriceListingCurrency(String priceListingCurrency) {
		this.priceListingCurrency = priceListingCurrency;
	}

	public BigDecimal getPriceListingAmount() {
		return this.priceListingAmount;
	}

	public void setPriceListingAmount(BigDecimal priceListingAmount) {
		this.priceListingAmount = priceListingAmount;
	}

	public String getPriceShippingCurrency() {
		return this.priceShippingCurrency;
	}

	public void setPriceShippingCurrency(String priceShippingCurrency) {
		this.priceShippingCurrency = priceShippingCurrency;
	}

	public BigDecimal getPriceShippingAmount() {
		return this.priceShippingAmount;
	}

	public void setPriceShippingAmount(BigDecimal priceShippingAmount) {
		this.priceShippingAmount = priceShippingAmount;
	}

	public String getFulfillmentChannel() {
		return this.fulfillmentChannel;
	}

	public void setFulfillmentChannel(String fulfillmentChannel) {
		this.fulfillmentChannel = fulfillmentChannel;
	}

	public String getItemCondition() {
		return this.itemCondition;
	}

	public void setItemCondition(String itemCondition) {
		this.itemCondition = itemCondition;
	}

	public String getItemSubcondition() {
		return this.itemSubcondition;
	}

	public void setItemSubcondition(String itemSubcondition) {
		this.itemSubcondition = itemSubcondition;
	}

	public String getSellerPositiveFeedbackRating() {
		return this.sellerPositiveFeedbackRating;
	}

	public void setSellerPositiveFeedbackRating(String sellerPositiveFeedbackRating) {
		this.sellerPositiveFeedbackRating = sellerPositiveFeedbackRating;
	}

	public String getShipsDomestically() {
		return this.shipsDomestically;
	}

	public void setShipsDomestically(String shipsDomestically) {
		this.shipsDomestically = shipsDomestically;
	}

	public String getMaxShippingTime() {
		return this.maxShippingTime;
	}

	public void setMaxShippingTime(String maxShippingTime) {
		this.maxShippingTime = maxShippingTime;
	}

}
