package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductCompetitivePricingData generated by hbm2java
 */
public class ProductCompetitivePricingData implements java.io.Serializable {

	private Integer id;
	private String status;
	private String asin;
	private String marketplaceId;
	private String sellerSku;
	private String sellerId;
	private Date tstamp;
	private Set productCompetitivePrices = new HashSet(0);
	private Set productOfferListings = new HashSet(0);
	private Set productCompetitiveLowestPricedOffersDatas = new HashSet(0);
	private Set productSalesRanks = new HashSet(0);

	public ProductCompetitivePricingData() {
	}

	public ProductCompetitivePricingData(String status, String asin, String marketplaceId, String sellerSku,
			String sellerId, Date tstamp, Set productCompetitivePrices, Set productOfferListings,
			Set productCompetitiveLowestPricedOffersDatas, Set productSalesRanks) {
		this.status = status;
		this.asin = asin;
		this.marketplaceId = marketplaceId;
		this.sellerSku = sellerSku;
		this.sellerId = sellerId;
		this.tstamp = tstamp;
		this.productCompetitivePrices = productCompetitivePrices;
		this.productOfferListings = productOfferListings;
		this.productCompetitiveLowestPricedOffersDatas = productCompetitiveLowestPricedOffersDatas;
		this.productSalesRanks = productSalesRanks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getAsin() {
		return this.asin;
	}

	public void setAsin(String asin) {
		this.asin = asin;
	}

	public String getMarketplaceId() {
		return this.marketplaceId;
	}

	public void setMarketplaceId(String marketplaceId) {
		this.marketplaceId = marketplaceId;
	}

	public String getSellerSku() {
		return this.sellerSku;
	}

	public void setSellerSku(String sellerSku) {
		this.sellerSku = sellerSku;
	}

	public String getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(String sellerId) {
		this.sellerId = sellerId;
	}

	public Date getTstamp() {
		return this.tstamp;
	}

	public void setTstamp(Date tstamp) {
		this.tstamp = tstamp;
	}

	public Set getProductCompetitivePrices() {
		return this.productCompetitivePrices;
	}

	public void setProductCompetitivePrices(Set productCompetitivePrices) {
		this.productCompetitivePrices = productCompetitivePrices;
	}

	public Set getProductOfferListings() {
		return this.productOfferListings;
	}

	public void setProductOfferListings(Set productOfferListings) {
		this.productOfferListings = productOfferListings;
	}

	public Set getProductCompetitiveLowestPricedOffersDatas() {
		return this.productCompetitiveLowestPricedOffersDatas;
	}

	public void setProductCompetitiveLowestPricedOffersDatas(Set productCompetitiveLowestPricedOffersDatas) {
		this.productCompetitiveLowestPricedOffersDatas = productCompetitiveLowestPricedOffersDatas;
	}

	public Set getProductSalesRanks() {
		return this.productSalesRanks;
	}

	public void setProductSalesRanks(Set productSalesRanks) {
		this.productSalesRanks = productSalesRanks;
	}

}
