package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * ProductOfferPriceData generated by hbm2java
 */
public class ProductOfferPriceData implements java.io.Serializable {

	private int id;
	private ProductLowestPricedOffersData productLowestPricedOffersData;
	private String conditions;
	private String fulfillmentChannel;
	private String landedPriceCurrency;
	private BigDecimal landedPriceAmount;
	private String listingPriceCurrency;
	private BigDecimal listingPriceAmount;
	private String shippingCurrency;
	private BigDecimal shippingAmount;
	private String isBuyBoxPrice;

	public ProductOfferPriceData() {
	}

	public ProductOfferPriceData(int id) {
		this.id = id;
	}

	public ProductOfferPriceData(int id, ProductLowestPricedOffersData productLowestPricedOffersData, String conditions,
			String fulfillmentChannel, String landedPriceCurrency, BigDecimal landedPriceAmount,
			String listingPriceCurrency, BigDecimal listingPriceAmount, String shippingCurrency,
			BigDecimal shippingAmount, String isBuyBoxPrice) {
		this.id = id;
		this.productLowestPricedOffersData = productLowestPricedOffersData;
		this.conditions = conditions;
		this.fulfillmentChannel = fulfillmentChannel;
		this.landedPriceCurrency = landedPriceCurrency;
		this.landedPriceAmount = landedPriceAmount;
		this.listingPriceCurrency = listingPriceCurrency;
		this.listingPriceAmount = listingPriceAmount;
		this.shippingCurrency = shippingCurrency;
		this.shippingAmount = shippingAmount;
		this.isBuyBoxPrice = isBuyBoxPrice;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ProductLowestPricedOffersData getProductLowestPricedOffersData() {
		return this.productLowestPricedOffersData;
	}

	public void setProductLowestPricedOffersData(ProductLowestPricedOffersData productLowestPricedOffersData) {
		this.productLowestPricedOffersData = productLowestPricedOffersData;
	}

	public String getConditions() {
		return this.conditions;
	}

	public void setConditions(String conditions) {
		this.conditions = conditions;
	}

	public String getFulfillmentChannel() {
		return this.fulfillmentChannel;
	}

	public void setFulfillmentChannel(String fulfillmentChannel) {
		this.fulfillmentChannel = fulfillmentChannel;
	}

	public String getLandedPriceCurrency() {
		return this.landedPriceCurrency;
	}

	public void setLandedPriceCurrency(String landedPriceCurrency) {
		this.landedPriceCurrency = landedPriceCurrency;
	}

	public BigDecimal getLandedPriceAmount() {
		return this.landedPriceAmount;
	}

	public void setLandedPriceAmount(BigDecimal landedPriceAmount) {
		this.landedPriceAmount = landedPriceAmount;
	}

	public String getListingPriceCurrency() {
		return this.listingPriceCurrency;
	}

	public void setListingPriceCurrency(String listingPriceCurrency) {
		this.listingPriceCurrency = listingPriceCurrency;
	}

	public BigDecimal getListingPriceAmount() {
		return this.listingPriceAmount;
	}

	public void setListingPriceAmount(BigDecimal listingPriceAmount) {
		this.listingPriceAmount = listingPriceAmount;
	}

	public String getShippingCurrency() {
		return this.shippingCurrency;
	}

	public void setShippingCurrency(String shippingCurrency) {
		this.shippingCurrency = shippingCurrency;
	}

	public BigDecimal getShippingAmount() {
		return this.shippingAmount;
	}

	public void setShippingAmount(BigDecimal shippingAmount) {
		this.shippingAmount = shippingAmount;
	}

	public String getIsBuyBoxPrice() {
		return this.isBuyBoxPrice;
	}

	public void setIsBuyBoxPrice(String isBuyBoxPrice) {
		this.isBuyBoxPrice = isBuyBoxPrice;
	}

}
