package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

/**
 * ProductOfferCountData generated by hbm2java
 */
public class ProductOfferCountData implements java.io.Serializable {

	private int id;
	private ProductLowestPricedOffersData productLowestPricedOffersData;
	private String conditions;
	private String fulfillmentChannel;
	private Integer offerCount;
	private String buyBoxEligible;

	public ProductOfferCountData() {
	}

	public ProductOfferCountData(int id) {
		this.id = id;
	}

	public ProductOfferCountData(int id, ProductLowestPricedOffersData productLowestPricedOffersData, String conditions,
			String fulfillmentChannel, Integer offerCount, String buyBoxEligible) {
		this.id = id;
		this.productLowestPricedOffersData = productLowestPricedOffersData;
		this.conditions = conditions;
		this.fulfillmentChannel = fulfillmentChannel;
		this.offerCount = offerCount;
		this.buyBoxEligible = buyBoxEligible;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ProductLowestPricedOffersData getProductLowestPricedOffersData() {
		return this.productLowestPricedOffersData;
	}

	public void setProductLowestPricedOffersData(ProductLowestPricedOffersData productLowestPricedOffersData) {
		this.productLowestPricedOffersData = productLowestPricedOffersData;
	}

	public String getConditions() {
		return this.conditions;
	}

	public void setConditions(String conditions) {
		this.conditions = conditions;
	}

	public String getFulfillmentChannel() {
		return this.fulfillmentChannel;
	}

	public void setFulfillmentChannel(String fulfillmentChannel) {
		this.fulfillmentChannel = fulfillmentChannel;
	}

	public Integer getOfferCount() {
		return this.offerCount;
	}

	public void setOfferCount(Integer offerCount) {
		this.offerCount = offerCount;
	}

	public String getBuyBoxEligible() {
		return this.buyBoxEligible;
	}

	public void setBuyBoxEligible(String buyBoxEligible) {
		this.buyBoxEligible = buyBoxEligible;
	}

}
