package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ProductAsinCategoryData generated by hbm2java
 */
public class ProductAsinCategoryData implements java.io.Serializable {

	private Integer id;
	private GeneralResponseRecord generalResponseRecord;
	private ProductCategories productCategories;
	private String asin;
	private Date tstamp;

	public ProductAsinCategoryData() {
	}

	public ProductAsinCategoryData(GeneralResponseRecord generalResponseRecord, ProductCategories productCategories,
			String asin, Date tstamp) {
		this.generalResponseRecord = generalResponseRecord;
		this.productCategories = productCategories;
		this.asin = asin;
		this.tstamp = tstamp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public GeneralResponseRecord getGeneralResponseRecord() {
		return this.generalResponseRecord;
	}

	public void setGeneralResponseRecord(GeneralResponseRecord generalResponseRecord) {
		this.generalResponseRecord = generalResponseRecord;
	}

	public ProductCategories getProductCategories() {
		return this.productCategories;
	}

	public void setProductCategories(ProductCategories productCategories) {
		this.productCategories = productCategories;
	}

	public String getAsin() {
		return this.asin;
	}

	public void setAsin(String asin) {
		this.asin = asin;
	}

	public Date getTstamp() {
		return this.tstamp;
	}

	public void setTstamp(Date tstamp) {
		this.tstamp = tstamp;
	}

}
