package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

/**
 * ProductSalesRank generated by hbm2java
 */
public class ProductSalesRank implements java.io.Serializable {

	private Integer id;
	private ProductCategories productCategories;
	private ProductCompetitivePricingData productCompetitivePricingData;
	private Integer rank;

	public ProductSalesRank() {
	}

	public ProductSalesRank(ProductCategories productCategories,
			ProductCompetitivePricingData productCompetitivePricingData, Integer rank) {
		this.productCategories = productCategories;
		this.productCompetitivePricingData = productCompetitivePricingData;
		this.rank = rank;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ProductCategories getProductCategories() {
		return this.productCategories;
	}

	public void setProductCategories(ProductCategories productCategories) {
		this.productCategories = productCategories;
	}

	public ProductCompetitivePricingData getProductCompetitivePricingData() {
		return this.productCompetitivePricingData;
	}

	public void setProductCompetitivePricingData(ProductCompetitivePricingData productCompetitivePricingData) {
		this.productCompetitivePricingData = productCompetitivePricingData;
	}

	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

}
