package dao.entities;
// Generated 2016-7-21 12:38:35 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * RecommendationOriginalData generated by hbm2java
 */
public class RecommendationOriginalData implements java.io.Serializable {

	private String recommendationId;
	private GeneralResponseRecord generalResponseRecord;
	private String recommendationReason;
	private Date lastUpdated;
	private String itemIdentifierAsin;
	private String itemIdentifierSku;
	private String itemIdentifierUpc;
	private String itemName;
	private String brandName;
	private String productCategory;
	private Integer salesRank;
	private String buyboxPriceCurrency;
	private BigDecimal buyboxPriceAmount;
	private Integer numberOfOffers;
	private Integer numberOfOffersFulfilledByAmazon;
	private BigDecimal averageCustomerReview;
	private Integer numberOfCustomerReviews;
	private BigDecimal itemDimensionsHeightValue;
	private String itemDimensionsHeightUnit;
	private BigDecimal itemDimensionsWidthValue;
	private String itemDimensionsWidthUnit;
	private BigDecimal itemDimensionsLengthValue;
	private String itemDimensionsLengthUnit;
	private BigDecimal itemDimensionsWeightValue;
	private String itemDimensionsWeightUnit;
	private String fulfillmentChannel;
	private Integer salesForTheLast30days;
	private Integer availableQuantity;
	private String yourPricePlusShippingCurrency;
	private BigDecimal yourPricePlusShippingAmount;
	private String lowestPricePlusShippingCurrency;
	private BigDecimal lowestPricePlusShippingAmount;
	private Integer salesForTheLast14days;
	private Integer daysUntilStockRunsOut;
	private Integer inboundQuantity;
	private Integer recommendedInboundQuantity;
	private Integer daysOutOfStockLast30days;
	private Integer lostSalesInLast30days;
	private String defectGroup;
	private String defectAttribute;
	private String qualitySet;
	private String itemCondition;
	private String subCondition;
	private String priceDifferenceToLowPriceCurrency;
	private BigDecimal priceDifferenceToLowPriceAmount;
	private String medianPricePlusShippingCurrency;
	private BigDecimal medianPricePlusShippingAmount;
	private String lowestMerchantFulfilledOfferPriceCurrency;
	private BigDecimal lowestMerchantFulfilledOfferPriceAmount;
	private String lowestAmazonFulfilledOfferPriceCurrency;
	private BigDecimal lowestAmazonFulfilledOfferPriceAmount;
	private Integer numberOfMerchantFulfilledOffers;
	private Integer numberOfAmazonFulfilledOffers;
	private String tstamp;

	public RecommendationOriginalData() {
	}

	public RecommendationOriginalData(String recommendationId) {
		this.recommendationId = recommendationId;
	}

	public RecommendationOriginalData(String recommendationId, GeneralResponseRecord generalResponseRecord,
			String recommendationReason, Date lastUpdated, String itemIdentifierAsin, String itemIdentifierSku,
			String itemIdentifierUpc, String itemName, String brandName, String productCategory, Integer salesRank,
			String buyboxPriceCurrency, BigDecimal buyboxPriceAmount, Integer numberOfOffers,
			Integer numberOfOffersFulfilledByAmazon, BigDecimal averageCustomerReview, Integer numberOfCustomerReviews,
			BigDecimal itemDimensionsHeightValue, String itemDimensionsHeightUnit, BigDecimal itemDimensionsWidthValue,
			String itemDimensionsWidthUnit, BigDecimal itemDimensionsLengthValue, String itemDimensionsLengthUnit,
			BigDecimal itemDimensionsWeightValue, String itemDimensionsWeightUnit, String fulfillmentChannel,
			Integer salesForTheLast30days, Integer availableQuantity, String yourPricePlusShippingCurrency,
			BigDecimal yourPricePlusShippingAmount, String lowestPricePlusShippingCurrency,
			BigDecimal lowestPricePlusShippingAmount, Integer salesForTheLast14days, Integer daysUntilStockRunsOut,
			Integer inboundQuantity, Integer recommendedInboundQuantity, Integer daysOutOfStockLast30days,
			Integer lostSalesInLast30days, String defectGroup, String defectAttribute, String qualitySet,
			String itemCondition, String subCondition, String priceDifferenceToLowPriceCurrency,
			BigDecimal priceDifferenceToLowPriceAmount, String medianPricePlusShippingCurrency,
			BigDecimal medianPricePlusShippingAmount, String lowestMerchantFulfilledOfferPriceCurrency,
			BigDecimal lowestMerchantFulfilledOfferPriceAmount, String lowestAmazonFulfilledOfferPriceCurrency,
			BigDecimal lowestAmazonFulfilledOfferPriceAmount, Integer numberOfMerchantFulfilledOffers,
			Integer numberOfAmazonFulfilledOffers, String tstamp) {
		this.recommendationId = recommendationId;
		this.generalResponseRecord = generalResponseRecord;
		this.recommendationReason = recommendationReason;
		this.lastUpdated = lastUpdated;
		this.itemIdentifierAsin = itemIdentifierAsin;
		this.itemIdentifierSku = itemIdentifierSku;
		this.itemIdentifierUpc = itemIdentifierUpc;
		this.itemName = itemName;
		this.brandName = brandName;
		this.productCategory = productCategory;
		this.salesRank = salesRank;
		this.buyboxPriceCurrency = buyboxPriceCurrency;
		this.buyboxPriceAmount = buyboxPriceAmount;
		this.numberOfOffers = numberOfOffers;
		this.numberOfOffersFulfilledByAmazon = numberOfOffersFulfilledByAmazon;
		this.averageCustomerReview = averageCustomerReview;
		this.numberOfCustomerReviews = numberOfCustomerReviews;
		this.itemDimensionsHeightValue = itemDimensionsHeightValue;
		this.itemDimensionsHeightUnit = itemDimensionsHeightUnit;
		this.itemDimensionsWidthValue = itemDimensionsWidthValue;
		this.itemDimensionsWidthUnit = itemDimensionsWidthUnit;
		this.itemDimensionsLengthValue = itemDimensionsLengthValue;
		this.itemDimensionsLengthUnit = itemDimensionsLengthUnit;
		this.itemDimensionsWeightValue = itemDimensionsWeightValue;
		this.itemDimensionsWeightUnit = itemDimensionsWeightUnit;
		this.fulfillmentChannel = fulfillmentChannel;
		this.salesForTheLast30days = salesForTheLast30days;
		this.availableQuantity = availableQuantity;
		this.yourPricePlusShippingCurrency = yourPricePlusShippingCurrency;
		this.yourPricePlusShippingAmount = yourPricePlusShippingAmount;
		this.lowestPricePlusShippingCurrency = lowestPricePlusShippingCurrency;
		this.lowestPricePlusShippingAmount = lowestPricePlusShippingAmount;
		this.salesForTheLast14days = salesForTheLast14days;
		this.daysUntilStockRunsOut = daysUntilStockRunsOut;
		this.inboundQuantity = inboundQuantity;
		this.recommendedInboundQuantity = recommendedInboundQuantity;
		this.daysOutOfStockLast30days = daysOutOfStockLast30days;
		this.lostSalesInLast30days = lostSalesInLast30days;
		this.defectGroup = defectGroup;
		this.defectAttribute = defectAttribute;
		this.qualitySet = qualitySet;
		this.itemCondition = itemCondition;
		this.subCondition = subCondition;
		this.priceDifferenceToLowPriceCurrency = priceDifferenceToLowPriceCurrency;
		this.priceDifferenceToLowPriceAmount = priceDifferenceToLowPriceAmount;
		this.medianPricePlusShippingCurrency = medianPricePlusShippingCurrency;
		this.medianPricePlusShippingAmount = medianPricePlusShippingAmount;
		this.lowestMerchantFulfilledOfferPriceCurrency = lowestMerchantFulfilledOfferPriceCurrency;
		this.lowestMerchantFulfilledOfferPriceAmount = lowestMerchantFulfilledOfferPriceAmount;
		this.lowestAmazonFulfilledOfferPriceCurrency = lowestAmazonFulfilledOfferPriceCurrency;
		this.lowestAmazonFulfilledOfferPriceAmount = lowestAmazonFulfilledOfferPriceAmount;
		this.numberOfMerchantFulfilledOffers = numberOfMerchantFulfilledOffers;
		this.numberOfAmazonFulfilledOffers = numberOfAmazonFulfilledOffers;
		this.tstamp = tstamp;
	}

	public String getRecommendationId() {
		return this.recommendationId;
	}

	public void setRecommendationId(String recommendationId) {
		this.recommendationId = recommendationId;
	}

	public GeneralResponseRecord getGeneralResponseRecord() {
		return this.generalResponseRecord;
	}

	public void setGeneralResponseRecord(GeneralResponseRecord generalResponseRecord) {
		this.generalResponseRecord = generalResponseRecord;
	}

	public String getRecommendationReason() {
		return this.recommendationReason;
	}

	public void setRecommendationReason(String recommendationReason) {
		this.recommendationReason = recommendationReason;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public String getItemIdentifierAsin() {
		return this.itemIdentifierAsin;
	}

	public void setItemIdentifierAsin(String itemIdentifierAsin) {
		this.itemIdentifierAsin = itemIdentifierAsin;
	}

	public String getItemIdentifierSku() {
		return this.itemIdentifierSku;
	}

	public void setItemIdentifierSku(String itemIdentifierSku) {
		this.itemIdentifierSku = itemIdentifierSku;
	}

	public String getItemIdentifierUpc() {
		return this.itemIdentifierUpc;
	}

	public void setItemIdentifierUpc(String itemIdentifierUpc) {
		this.itemIdentifierUpc = itemIdentifierUpc;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	public String getProductCategory() {
		return this.productCategory;
	}

	public void setProductCategory(String productCategory) {
		this.productCategory = productCategory;
	}

	public Integer getSalesRank() {
		return this.salesRank;
	}

	public void setSalesRank(Integer salesRank) {
		this.salesRank = salesRank;
	}

	public String getBuyboxPriceCurrency() {
		return this.buyboxPriceCurrency;
	}

	public void setBuyboxPriceCurrency(String buyboxPriceCurrency) {
		this.buyboxPriceCurrency = buyboxPriceCurrency;
	}

	public BigDecimal getBuyboxPriceAmount() {
		return this.buyboxPriceAmount;
	}

	public void setBuyboxPriceAmount(BigDecimal buyboxPriceAmount) {
		this.buyboxPriceAmount = buyboxPriceAmount;
	}

	public Integer getNumberOfOffers() {
		return this.numberOfOffers;
	}

	public void setNumberOfOffers(Integer numberOfOffers) {
		this.numberOfOffers = numberOfOffers;
	}

	public Integer getNumberOfOffersFulfilledByAmazon() {
		return this.numberOfOffersFulfilledByAmazon;
	}

	public void setNumberOfOffersFulfilledByAmazon(Integer numberOfOffersFulfilledByAmazon) {
		this.numberOfOffersFulfilledByAmazon = numberOfOffersFulfilledByAmazon;
	}

	public BigDecimal getAverageCustomerReview() {
		return this.averageCustomerReview;
	}

	public void setAverageCustomerReview(BigDecimal averageCustomerReview) {
		this.averageCustomerReview = averageCustomerReview;
	}

	public Integer getNumberOfCustomerReviews() {
		return this.numberOfCustomerReviews;
	}

	public void setNumberOfCustomerReviews(Integer numberOfCustomerReviews) {
		this.numberOfCustomerReviews = numberOfCustomerReviews;
	}

	public BigDecimal getItemDimensionsHeightValue() {
		return this.itemDimensionsHeightValue;
	}

	public void setItemDimensionsHeightValue(BigDecimal itemDimensionsHeightValue) {
		this.itemDimensionsHeightValue = itemDimensionsHeightValue;
	}

	public String getItemDimensionsHeightUnit() {
		return this.itemDimensionsHeightUnit;
	}

	public void setItemDimensionsHeightUnit(String itemDimensionsHeightUnit) {
		this.itemDimensionsHeightUnit = itemDimensionsHeightUnit;
	}

	public BigDecimal getItemDimensionsWidthValue() {
		return this.itemDimensionsWidthValue;
	}

	public void setItemDimensionsWidthValue(BigDecimal itemDimensionsWidthValue) {
		this.itemDimensionsWidthValue = itemDimensionsWidthValue;
	}

	public String getItemDimensionsWidthUnit() {
		return this.itemDimensionsWidthUnit;
	}

	public void setItemDimensionsWidthUnit(String itemDimensionsWidthUnit) {
		this.itemDimensionsWidthUnit = itemDimensionsWidthUnit;
	}

	public BigDecimal getItemDimensionsLengthValue() {
		return this.itemDimensionsLengthValue;
	}

	public void setItemDimensionsLengthValue(BigDecimal itemDimensionsLengthValue) {
		this.itemDimensionsLengthValue = itemDimensionsLengthValue;
	}

	public String getItemDimensionsLengthUnit() {
		return this.itemDimensionsLengthUnit;
	}

	public void setItemDimensionsLengthUnit(String itemDimensionsLengthUnit) {
		this.itemDimensionsLengthUnit = itemDimensionsLengthUnit;
	}

	public BigDecimal getItemDimensionsWeightValue() {
		return this.itemDimensionsWeightValue;
	}

	public void setItemDimensionsWeightValue(BigDecimal itemDimensionsWeightValue) {
		this.itemDimensionsWeightValue = itemDimensionsWeightValue;
	}

	public String getItemDimensionsWeightUnit() {
		return this.itemDimensionsWeightUnit;
	}

	public void setItemDimensionsWeightUnit(String itemDimensionsWeightUnit) {
		this.itemDimensionsWeightUnit = itemDimensionsWeightUnit;
	}

	public String getFulfillmentChannel() {
		return this.fulfillmentChannel;
	}

	public void setFulfillmentChannel(String fulfillmentChannel) {
		this.fulfillmentChannel = fulfillmentChannel;
	}

	public Integer getSalesForTheLast30days() {
		return this.salesForTheLast30days;
	}

	public void setSalesForTheLast30days(Integer salesForTheLast30days) {
		this.salesForTheLast30days = salesForTheLast30days;
	}

	public Integer getAvailableQuantity() {
		return this.availableQuantity;
	}

	public void setAvailableQuantity(Integer availableQuantity) {
		this.availableQuantity = availableQuantity;
	}

	public String getYourPricePlusShippingCurrency() {
		return this.yourPricePlusShippingCurrency;
	}

	public void setYourPricePlusShippingCurrency(String yourPricePlusShippingCurrency) {
		this.yourPricePlusShippingCurrency = yourPricePlusShippingCurrency;
	}

	public BigDecimal getYourPricePlusShippingAmount() {
		return this.yourPricePlusShippingAmount;
	}

	public void setYourPricePlusShippingAmount(BigDecimal yourPricePlusShippingAmount) {
		this.yourPricePlusShippingAmount = yourPricePlusShippingAmount;
	}

	public String getLowestPricePlusShippingCurrency() {
		return this.lowestPricePlusShippingCurrency;
	}

	public void setLowestPricePlusShippingCurrency(String lowestPricePlusShippingCurrency) {
		this.lowestPricePlusShippingCurrency = lowestPricePlusShippingCurrency;
	}

	public BigDecimal getLowestPricePlusShippingAmount() {
		return this.lowestPricePlusShippingAmount;
	}

	public void setLowestPricePlusShippingAmount(BigDecimal lowestPricePlusShippingAmount) {
		this.lowestPricePlusShippingAmount = lowestPricePlusShippingAmount;
	}

	public Integer getSalesForTheLast14days() {
		return this.salesForTheLast14days;
	}

	public void setSalesForTheLast14days(Integer salesForTheLast14days) {
		this.salesForTheLast14days = salesForTheLast14days;
	}

	public Integer getDaysUntilStockRunsOut() {
		return this.daysUntilStockRunsOut;
	}

	public void setDaysUntilStockRunsOut(Integer daysUntilStockRunsOut) {
		this.daysUntilStockRunsOut = daysUntilStockRunsOut;
	}

	public Integer getInboundQuantity() {
		return this.inboundQuantity;
	}

	public void setInboundQuantity(Integer inboundQuantity) {
		this.inboundQuantity = inboundQuantity;
	}

	public Integer getRecommendedInboundQuantity() {
		return this.recommendedInboundQuantity;
	}

	public void setRecommendedInboundQuantity(Integer recommendedInboundQuantity) {
		this.recommendedInboundQuantity = recommendedInboundQuantity;
	}

	public Integer getDaysOutOfStockLast30days() {
		return this.daysOutOfStockLast30days;
	}

	public void setDaysOutOfStockLast30days(Integer daysOutOfStockLast30days) {
		this.daysOutOfStockLast30days = daysOutOfStockLast30days;
	}

	public Integer getLostSalesInLast30days() {
		return this.lostSalesInLast30days;
	}

	public void setLostSalesInLast30days(Integer lostSalesInLast30days) {
		this.lostSalesInLast30days = lostSalesInLast30days;
	}

	public String getDefectGroup() {
		return this.defectGroup;
	}

	public void setDefectGroup(String defectGroup) {
		this.defectGroup = defectGroup;
	}

	public String getDefectAttribute() {
		return this.defectAttribute;
	}

	public void setDefectAttribute(String defectAttribute) {
		this.defectAttribute = defectAttribute;
	}

	public String getQualitySet() {
		return this.qualitySet;
	}

	public void setQualitySet(String qualitySet) {
		this.qualitySet = qualitySet;
	}

	public String getItemCondition() {
		return this.itemCondition;
	}

	public void setItemCondition(String itemCondition) {
		this.itemCondition = itemCondition;
	}

	public String getSubCondition() {
		return this.subCondition;
	}

	public void setSubCondition(String subCondition) {
		this.subCondition = subCondition;
	}

	public String getPriceDifferenceToLowPriceCurrency() {
		return this.priceDifferenceToLowPriceCurrency;
	}

	public void setPriceDifferenceToLowPriceCurrency(String priceDifferenceToLowPriceCurrency) {
		this.priceDifferenceToLowPriceCurrency = priceDifferenceToLowPriceCurrency;
	}

	public BigDecimal getPriceDifferenceToLowPriceAmount() {
		return this.priceDifferenceToLowPriceAmount;
	}

	public void setPriceDifferenceToLowPriceAmount(BigDecimal priceDifferenceToLowPriceAmount) {
		this.priceDifferenceToLowPriceAmount = priceDifferenceToLowPriceAmount;
	}

	public String getMedianPricePlusShippingCurrency() {
		return this.medianPricePlusShippingCurrency;
	}

	public void setMedianPricePlusShippingCurrency(String medianPricePlusShippingCurrency) {
		this.medianPricePlusShippingCurrency = medianPricePlusShippingCurrency;
	}

	public BigDecimal getMedianPricePlusShippingAmount() {
		return this.medianPricePlusShippingAmount;
	}

	public void setMedianPricePlusShippingAmount(BigDecimal medianPricePlusShippingAmount) {
		this.medianPricePlusShippingAmount = medianPricePlusShippingAmount;
	}

	public String getLowestMerchantFulfilledOfferPriceCurrency() {
		return this.lowestMerchantFulfilledOfferPriceCurrency;
	}

	public void setLowestMerchantFulfilledOfferPriceCurrency(String lowestMerchantFulfilledOfferPriceCurrency) {
		this.lowestMerchantFulfilledOfferPriceCurrency = lowestMerchantFulfilledOfferPriceCurrency;
	}

	public BigDecimal getLowestMerchantFulfilledOfferPriceAmount() {
		return this.lowestMerchantFulfilledOfferPriceAmount;
	}

	public void setLowestMerchantFulfilledOfferPriceAmount(BigDecimal lowestMerchantFulfilledOfferPriceAmount) {
		this.lowestMerchantFulfilledOfferPriceAmount = lowestMerchantFulfilledOfferPriceAmount;
	}

	public String getLowestAmazonFulfilledOfferPriceCurrency() {
		return this.lowestAmazonFulfilledOfferPriceCurrency;
	}

	public void setLowestAmazonFulfilledOfferPriceCurrency(String lowestAmazonFulfilledOfferPriceCurrency) {
		this.lowestAmazonFulfilledOfferPriceCurrency = lowestAmazonFulfilledOfferPriceCurrency;
	}

	public BigDecimal getLowestAmazonFulfilledOfferPriceAmount() {
		return this.lowestAmazonFulfilledOfferPriceAmount;
	}

	public void setLowestAmazonFulfilledOfferPriceAmount(BigDecimal lowestAmazonFulfilledOfferPriceAmount) {
		this.lowestAmazonFulfilledOfferPriceAmount = lowestAmazonFulfilledOfferPriceAmount;
	}

	public Integer getNumberOfMerchantFulfilledOffers() {
		return this.numberOfMerchantFulfilledOffers;
	}

	public void setNumberOfMerchantFulfilledOffers(Integer numberOfMerchantFulfilledOffers) {
		this.numberOfMerchantFulfilledOffers = numberOfMerchantFulfilledOffers;
	}

	public Integer getNumberOfAmazonFulfilledOffers() {
		return this.numberOfAmazonFulfilledOffers;
	}

	public void setNumberOfAmazonFulfilledOffers(Integer numberOfAmazonFulfilledOffers) {
		this.numberOfAmazonFulfilledOffers = numberOfAmazonFulfilledOffers;
	}

	public String getTstamp() {
		return this.tstamp;
	}

	public void setTstamp(String tstamp) {
		this.tstamp = tstamp;
	}

}
