package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ReportGetReportTask generated by hbm2java
 */
public class ReportGetReportTask implements java.io.Serializable {

	private Integer id;
	private String merchant;
	private Date workDate;
	private String reportType;
	private String status;
	private String reportProcessingStatus;
	private Date fromDate;
	private Date toDate;
	private String outputPath;
	private String reportRequestId;
	private String reportId;
	private Date lastUpdateDatetime;

	public ReportGetReportTask() {
	}

	public ReportGetReportTask(String merchant, Date workDate, String reportType, String status,
			String reportProcessingStatus, Date fromDate, Date toDate, String outputPath, String reportRequestId,
			String reportId, Date lastUpdateDatetime) {
		this.merchant = merchant;
		this.workDate = workDate;
		this.reportType = reportType;
		this.status = status;
		this.reportProcessingStatus = reportProcessingStatus;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.outputPath = outputPath;
		this.reportRequestId = reportRequestId;
		this.reportId = reportId;
		this.lastUpdateDatetime = lastUpdateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMerchant() {
		return this.merchant;
	}

	public void setMerchant(String merchant) {
		this.merchant = merchant;
	}

	public Date getWorkDate() {
		return this.workDate;
	}

	public void setWorkDate(Date workDate) {
		this.workDate = workDate;
	}

	public String getReportType() {
		return this.reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getReportProcessingStatus() {
		return this.reportProcessingStatus;
	}

	public void setReportProcessingStatus(String reportProcessingStatus) {
		this.reportProcessingStatus = reportProcessingStatus;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public String getOutputPath() {
		return this.outputPath;
	}

	public void setOutputPath(String outputPath) {
		this.outputPath = outputPath;
	}

	public String getReportRequestId() {
		return this.reportRequestId;
	}

	public void setReportRequestId(String reportRequestId) {
		this.reportRequestId = reportRequestId;
	}

	public String getReportId() {
		return this.reportId;
	}

	public void setReportId(String reportId) {
		this.reportId = reportId;
	}

	public Date getLastUpdateDatetime() {
		return this.lastUpdateDatetime;
	}

	public void setLastUpdateDatetime(Date lastUpdateDatetime) {
		this.lastUpdateDatetime = lastUpdateDatetime;
	}

}
