package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

/**
 * ReportDailyTaskTemplate generated by hbm2java
 */
public class ReportDailyTaskTemplate implements java.io.Serializable {

	private Integer id;
	private String reportType;
	private Integer distanceDays;
	private Integer startDateSetRequired;
	private Integer endDateSetRequired;
	private Integer enabled;

	public ReportDailyTaskTemplate() {
	}

	public ReportDailyTaskTemplate(String reportType, Integer distanceDays, Integer startDateSetRequired,
			Integer endDateSetRequired, Integer enabled) {
		this.reportType = reportType;
		this.distanceDays = distanceDays;
		this.startDateSetRequired = startDateSetRequired;
		this.endDateSetRequired = endDateSetRequired;
		this.enabled = enabled;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getReportType() {
		return this.reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	public Integer getDistanceDays() {
		return this.distanceDays;
	}

	public void setDistanceDays(Integer distanceDays) {
		this.distanceDays = distanceDays;
	}

	public Integer getStartDateSetRequired() {
		return this.startDateSetRequired;
	}

	public void setStartDateSetRequired(Integer startDateSetRequired) {
		this.startDateSetRequired = startDateSetRequired;
	}

	public Integer getEndDateSetRequired() {
		return this.endDateSetRequired;
	}

	public void setEndDateSetRequired(Integer endDateSetRequired) {
		this.endDateSetRequired = endDateSetRequired;
	}

	public Integer getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Integer enabled) {
		this.enabled = enabled;
	}

}
