package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ReportFeedback generated by hbm2java
 */
public class ReportFeedback implements java.io.Serializable {

	private Integer id;
	private String store;
	private Date insertDate;
	private String date;
	private String rating;
	private String comments;
	private String yourResponse;
	private String arrivedOnTime;
	private String itemAsDescribed;
	private String customerService;
	private String orderId;
	private String raterEmail;
	private String raterRole;

	public ReportFeedback() {
	}

	public ReportFeedback(String store, Date insertDate, String date, String rating, String comments,
			String yourResponse, String arrivedOnTime, String itemAsDescribed, String customerService, String orderId,
			String raterEmail, String raterRole) {
		this.store = store;
		this.insertDate = insertDate;
		this.date = date;
		this.rating = rating;
		this.comments = comments;
		this.yourResponse = yourResponse;
		this.arrivedOnTime = arrivedOnTime;
		this.itemAsDescribed = itemAsDescribed;
		this.customerService = customerService;
		this.orderId = orderId;
		this.raterEmail = raterEmail;
		this.raterRole = raterRole;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStore() {
		return this.store;
	}

	public void setStore(String store) {
		this.store = store;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getRating() {
		return this.rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getYourResponse() {
		return this.yourResponse;
	}

	public void setYourResponse(String yourResponse) {
		this.yourResponse = yourResponse;
	}

	public String getArrivedOnTime() {
		return this.arrivedOnTime;
	}

	public void setArrivedOnTime(String arrivedOnTime) {
		this.arrivedOnTime = arrivedOnTime;
	}

	public String getItemAsDescribed() {
		return this.itemAsDescribed;
	}

	public void setItemAsDescribed(String itemAsDescribed) {
		this.itemAsDescribed = itemAsDescribed;
	}

	public String getCustomerService() {
		return this.customerService;
	}

	public void setCustomerService(String customerService) {
		this.customerService = customerService;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getRaterEmail() {
		return this.raterEmail;
	}

	public void setRaterEmail(String raterEmail) {
		this.raterEmail = raterEmail;
	}

	public String getRaterRole() {
		return this.raterRole;
	}

	public void setRaterRole(String raterRole) {
		this.raterRole = raterRole;
	}

}
