package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * ReportCancelledListings generated by hbm2java
 */
public class ReportCancelledListings implements java.io.Serializable {

	private String sellerSku;
	private String store;
	private Date insertDate;
	private String itemName;
	private BigDecimal price;
	private Integer quantity;
	private String imageUrl;
	private String itemIsMarketplace;
	private String productIdType;
	private BigDecimal zshipShippingFee;
	private String itemNote;
	private String itemCondition;
	private String zshopCategory1;
	private String zshopBrowsePath;
	private String zshopStorefrontFeature;
	private String asin1;
	private String asin2;
	private String asin3;
	private String willShipInternationally;
	private String expeditedShipping;
	private String zshipBoldface;
	private String productId;
	private String addDelete;

	public ReportCancelledListings() {
	}

	public ReportCancelledListings(String sellerSku) {
		this.sellerSku = sellerSku;
	}

	public ReportCancelledListings(String sellerSku, String store, Date insertDate, String itemName, BigDecimal price,
			Integer quantity, String imageUrl, String itemIsMarketplace, String productIdType,
			BigDecimal zshipShippingFee, String itemNote, String itemCondition, String zshopCategory1,
			String zshopBrowsePath, String zshopStorefrontFeature, String asin1, String asin2, String asin3,
			String willShipInternationally, String expeditedShipping, String zshipBoldface, String productId,
			String addDelete) {
		this.sellerSku = sellerSku;
		this.store = store;
		this.insertDate = insertDate;
		this.itemName = itemName;
		this.price = price;
		this.quantity = quantity;
		this.imageUrl = imageUrl;
		this.itemIsMarketplace = itemIsMarketplace;
		this.productIdType = productIdType;
		this.zshipShippingFee = zshipShippingFee;
		this.itemNote = itemNote;
		this.itemCondition = itemCondition;
		this.zshopCategory1 = zshopCategory1;
		this.zshopBrowsePath = zshopBrowsePath;
		this.zshopStorefrontFeature = zshopStorefrontFeature;
		this.asin1 = asin1;
		this.asin2 = asin2;
		this.asin3 = asin3;
		this.willShipInternationally = willShipInternationally;
		this.expeditedShipping = expeditedShipping;
		this.zshipBoldface = zshipBoldface;
		this.productId = productId;
		this.addDelete = addDelete;
	}

	public String getSellerSku() {
		return this.sellerSku;
	}

	public void setSellerSku(String sellerSku) {
		this.sellerSku = sellerSku;
	}

	public String getStore() {
		return this.store;
	}

	public void setStore(String store) {
		this.store = store;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public String getItemIsMarketplace() {
		return this.itemIsMarketplace;
	}

	public void setItemIsMarketplace(String itemIsMarketplace) {
		this.itemIsMarketplace = itemIsMarketplace;
	}

	public String getProductIdType() {
		return this.productIdType;
	}

	public void setProductIdType(String productIdType) {
		this.productIdType = productIdType;
	}

	public BigDecimal getZshipShippingFee() {
		return this.zshipShippingFee;
	}

	public void setZshipShippingFee(BigDecimal zshipShippingFee) {
		this.zshipShippingFee = zshipShippingFee;
	}

	public String getItemNote() {
		return this.itemNote;
	}

	public void setItemNote(String itemNote) {
		this.itemNote = itemNote;
	}

	public String getItemCondition() {
		return this.itemCondition;
	}

	public void setItemCondition(String itemCondition) {
		this.itemCondition = itemCondition;
	}

	public String getZshopCategory1() {
		return this.zshopCategory1;
	}

	public void setZshopCategory1(String zshopCategory1) {
		this.zshopCategory1 = zshopCategory1;
	}

	public String getZshopBrowsePath() {
		return this.zshopBrowsePath;
	}

	public void setZshopBrowsePath(String zshopBrowsePath) {
		this.zshopBrowsePath = zshopBrowsePath;
	}

	public String getZshopStorefrontFeature() {
		return this.zshopStorefrontFeature;
	}

	public void setZshopStorefrontFeature(String zshopStorefrontFeature) {
		this.zshopStorefrontFeature = zshopStorefrontFeature;
	}

	public String getAsin1() {
		return this.asin1;
	}

	public void setAsin1(String asin1) {
		this.asin1 = asin1;
	}

	public String getAsin2() {
		return this.asin2;
	}

	public void setAsin2(String asin2) {
		this.asin2 = asin2;
	}

	public String getAsin3() {
		return this.asin3;
	}

	public void setAsin3(String asin3) {
		this.asin3 = asin3;
	}

	public String getWillShipInternationally() {
		return this.willShipInternationally;
	}

	public void setWillShipInternationally(String willShipInternationally) {
		this.willShipInternationally = willShipInternationally;
	}

	public String getExpeditedShipping() {
		return this.expeditedShipping;
	}

	public void setExpeditedShipping(String expeditedShipping) {
		this.expeditedShipping = expeditedShipping;
	}

	public String getZshipBoldface() {
		return this.zshipBoldface;
	}

	public void setZshipBoldface(String zshipBoldface) {
		this.zshipBoldface = zshipBoldface;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getAddDelete() {
		return this.addDelete;
	}

	public void setAddDelete(String addDelete) {
		this.addDelete = addDelete;
	}

}
