package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * ReportAdsProductPerformanceDaily generated by hbm2java
 */
public class ReportAdsProductPerformanceDaily implements java.io.Serializable {

	private Integer id;
	private String store;
	private Date insertDate;
	private Date startDate;
	private Date endDate;
	private String merchantName;
	private String sku;
	private Integer clicks;
	private Integer impressions;
	private String ctr;
	private String currency;
	private BigDecimal totalSpend;
	private String avgCpc;

	public ReportAdsProductPerformanceDaily() {
	}

	public ReportAdsProductPerformanceDaily(String store, Date insertDate, Date startDate, Date endDate,
			String merchantName, String sku, Integer clicks, Integer impressions, String ctr, String currency,
			BigDecimal totalSpend, String avgCpc) {
		this.store = store;
		this.insertDate = insertDate;
		this.startDate = startDate;
		this.endDate = endDate;
		this.merchantName = merchantName;
		this.sku = sku;
		this.clicks = clicks;
		this.impressions = impressions;
		this.ctr = ctr;
		this.currency = currency;
		this.totalSpend = totalSpend;
		this.avgCpc = avgCpc;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStore() {
		return this.store;
	}

	public void setStore(String store) {
		this.store = store;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getMerchantName() {
		return this.merchantName;
	}

	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName;
	}

	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	public Integer getClicks() {
		return this.clicks;
	}

	public void setClicks(Integer clicks) {
		this.clicks = clicks;
	}

	public Integer getImpressions() {
		return this.impressions;
	}

	public void setImpressions(Integer impressions) {
		this.impressions = impressions;
	}

	public String getCtr() {
		return this.ctr;
	}

	public void setCtr(String ctr) {
		this.ctr = ctr;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public BigDecimal getTotalSpend() {
		return this.totalSpend;
	}

	public void setTotalSpend(BigDecimal totalSpend) {
		this.totalSpend = totalSpend;
	}

	public String getAvgCpc() {
		return this.avgCpc;
	}

	public void setAvgCpc(String avgCpc) {
		this.avgCpc = avgCpc;
	}

}
