package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * ReportAdsOtherAsinWeekly generated by hbm2java
 */
public class ReportAdsOtherAsinWeekly implements java.io.Serializable {

	private Integer id;
	private String store;
	private Date insertDate;
	private Date startDate;
	private Date endDate;
	private String campaignName;
	private String adGroupName;
	private String advertisedSku;
	private String advertisedAsin;
	private String keyword;
	private String matchType;
	private String otherAsin;
	private String currency;
	private Integer oneMonthOtherAsinUnitsOrdered;
	private BigDecimal oneMonthOtherAsinUnitsOrderedProductSales;

	public ReportAdsOtherAsinWeekly() {
	}

	public ReportAdsOtherAsinWeekly(String store, Date insertDate, Date startDate, Date endDate, String campaignName,
			String adGroupName, String advertisedSku, String advertisedAsin, String keyword, String matchType,
			String otherAsin, String currency, Integer oneMonthOtherAsinUnitsOrdered,
			BigDecimal oneMonthOtherAsinUnitsOrderedProductSales) {
		this.store = store;
		this.insertDate = insertDate;
		this.startDate = startDate;
		this.endDate = endDate;
		this.campaignName = campaignName;
		this.adGroupName = adGroupName;
		this.advertisedSku = advertisedSku;
		this.advertisedAsin = advertisedAsin;
		this.keyword = keyword;
		this.matchType = matchType;
		this.otherAsin = otherAsin;
		this.currency = currency;
		this.oneMonthOtherAsinUnitsOrdered = oneMonthOtherAsinUnitsOrdered;
		this.oneMonthOtherAsinUnitsOrderedProductSales = oneMonthOtherAsinUnitsOrderedProductSales;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStore() {
		return this.store;
	}

	public void setStore(String store) {
		this.store = store;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getCampaignName() {
		return this.campaignName;
	}

	public void setCampaignName(String campaignName) {
		this.campaignName = campaignName;
	}

	public String getAdGroupName() {
		return this.adGroupName;
	}

	public void setAdGroupName(String adGroupName) {
		this.adGroupName = adGroupName;
	}

	public String getAdvertisedSku() {
		return this.advertisedSku;
	}

	public void setAdvertisedSku(String advertisedSku) {
		this.advertisedSku = advertisedSku;
	}

	public String getAdvertisedAsin() {
		return this.advertisedAsin;
	}

	public void setAdvertisedAsin(String advertisedAsin) {
		this.advertisedAsin = advertisedAsin;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public String getMatchType() {
		return this.matchType;
	}

	public void setMatchType(String matchType) {
		this.matchType = matchType;
	}

	public String getOtherAsin() {
		return this.otherAsin;
	}

	public void setOtherAsin(String otherAsin) {
		this.otherAsin = otherAsin;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public Integer getOneMonthOtherAsinUnitsOrdered() {
		return this.oneMonthOtherAsinUnitsOrdered;
	}

	public void setOneMonthOtherAsinUnitsOrdered(Integer oneMonthOtherAsinUnitsOrdered) {
		this.oneMonthOtherAsinUnitsOrdered = oneMonthOtherAsinUnitsOrdered;
	}

	public BigDecimal getOneMonthOtherAsinUnitsOrderedProductSales() {
		return this.oneMonthOtherAsinUnitsOrderedProductSales;
	}

	public void setOneMonthOtherAsinUnitsOrderedProductSales(BigDecimal oneMonthOtherAsinUnitsOrderedProductSales) {
		this.oneMonthOtherAsinUnitsOrderedProductSales = oneMonthOtherAsinUnitsOrderedProductSales;
	}

}
