package dao.entities;
// Generated 2016-8-5 10:25:53 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ReportAdsBidByKeywordId generated by hbm2java
 */
public class ReportAdsBidByKeywordId implements java.io.Serializable {

	private String store;
	private Date reportDate;
	private String campaignName;
	private String adGroupName;
	private String keyword;
	private String yourMaximunCpcBid;
	private String estPage1Bid;

	public ReportAdsBidByKeywordId() {
	}

	public ReportAdsBidByKeywordId(String store, Date reportDate, String campaignName, String adGroupName,
			String keyword, String yourMaximunCpcBid, String estPage1Bid) {
		this.store = store;
		this.reportDate = reportDate;
		this.campaignName = campaignName;
		this.adGroupName = adGroupName;
		this.keyword = keyword;
		this.yourMaximunCpcBid = yourMaximunCpcBid;
		this.estPage1Bid = estPage1Bid;
	}

	public String getStore() {
		return this.store;
	}

	public void setStore(String store) {
		this.store = store;
	}

	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	public String getCampaignName() {
		return this.campaignName;
	}

	public void setCampaignName(String campaignName) {
		this.campaignName = campaignName;
	}

	public String getAdGroupName() {
		return this.adGroupName;
	}

	public void setAdGroupName(String adGroupName) {
		this.adGroupName = adGroupName;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public String getYourMaximunCpcBid() {
		return this.yourMaximunCpcBid;
	}

	public void setYourMaximunCpcBid(String yourMaximunCpcBid) {
		this.yourMaximunCpcBid = yourMaximunCpcBid;
	}

	public String getEstPage1Bid() {
		return this.estPage1Bid;
	}

	public void setEstPage1Bid(String estPage1Bid) {
		this.estPage1Bid = estPage1Bid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReportAdsBidByKeywordId))
			return false;
		ReportAdsBidByKeywordId castOther = (ReportAdsBidByKeywordId) other;

		return ((this.getStore() == castOther.getStore()) || (this.getStore() != null && castOther.getStore() != null
				&& this.getStore().equals(castOther.getStore())))
				&& ((this.getReportDate() == castOther.getReportDate()) || (this.getReportDate() != null
						&& castOther.getReportDate() != null && this.getReportDate().equals(castOther.getReportDate())))
				&& ((this.getCampaignName() == castOther.getCampaignName())
						|| (this.getCampaignName() != null && castOther.getCampaignName() != null
								&& this.getCampaignName().equals(castOther.getCampaignName())))
				&& ((this.getAdGroupName() == castOther.getAdGroupName())
						|| (this.getAdGroupName() != null && castOther.getAdGroupName() != null
								&& this.getAdGroupName().equals(castOther.getAdGroupName())))
				&& ((this.getKeyword() == castOther.getKeyword()) || (this.getKeyword() != null
						&& castOther.getKeyword() != null && this.getKeyword().equals(castOther.getKeyword())))
				&& ((this.getYourMaximunCpcBid() == castOther.getYourMaximunCpcBid())
						|| (this.getYourMaximunCpcBid() != null && castOther.getYourMaximunCpcBid() != null
								&& this.getYourMaximunCpcBid().equals(castOther.getYourMaximunCpcBid())))
				&& ((this.getEstPage1Bid() == castOther.getEstPage1Bid())
						|| (this.getEstPage1Bid() != null && castOther.getEstPage1Bid() != null
								&& this.getEstPage1Bid().equals(castOther.getEstPage1Bid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStore() == null ? 0 : this.getStore().hashCode());
		result = 37 * result + (getReportDate() == null ? 0 : this.getReportDate().hashCode());
		result = 37 * result + (getCampaignName() == null ? 0 : this.getCampaignName().hashCode());
		result = 37 * result + (getAdGroupName() == null ? 0 : this.getAdGroupName().hashCode());
		result = 37 * result + (getKeyword() == null ? 0 : this.getKeyword().hashCode());
		result = 37 * result + (getYourMaximunCpcBid() == null ? 0 : this.getYourMaximunCpcBid().hashCode());
		result = 37 * result + (getEstPage1Bid() == null ? 0 : this.getEstPage1Bid().hashCode());
		return result;
	}

}
