package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * ReportAdsMega generated by hbm2java
 */
public class ReportAdsMega implements java.io.Serializable {

	private Integer id;
	private String store;
	private Date insertDate;
	private String campaignName;
	private String adGroupName;
	private String advertisedSku;
	private String keyword;
	private String matchType;
	private Date startDate;
	private Date endDate;
	private Integer clicks;
	private Integer impressions;
	private String ctr;
	private BigDecimal totalSpend;
	private String averageCpc;
	private String currency;
	private Integer oneDayOrdersPlaced;
	private BigDecimal oneDayOrderedProductSales;
	private String oneDayConversionRate;
	private Integer oneDaySameSkuUnitsOrdered;
	private Integer oneDayOtherSkuUnitsOrdered;
	private BigDecimal oneDaySameSkuUnitsOrderedProductSales;
	private BigDecimal oneDayOtherSkuUnitsOrderedProductSales;
	private Integer oneWeekOrdersPlaced;
	private BigDecimal oneWeekOrderedProductSales;
	private String oneWeekConversionRate;
	private Integer oneWeekSameSkuUnitsOrdered;
	private Integer oneWeekOtherSkuUnitsOrdered;
	private BigDecimal oneWeekSameSkuUnitsOrderedProductSales;
	private BigDecimal oneWeekOtherSkuUnitsOrderedProductSales;
	private Integer oneMonthOrdersPlaced;
	private BigDecimal oneMonthOrderedProductSales;
	private String oneMonthConversionRate;
	private Integer oneMonthSameSkuUnitsOrdered;
	private Integer oneMonthOtherSkuUnitsOrdered;
	private BigDecimal oneMonthSameSkuUnitsOrderedProductSales;
	private BigDecimal oneMonthOtherSkuUnitsOrderedProductSales;

	public ReportAdsMega() {
	}

	public ReportAdsMega(String store, Date insertDate, String campaignName, String adGroupName, String advertisedSku,
			String keyword, String matchType, Date startDate, Date endDate, Integer clicks, Integer impressions,
			String ctr, BigDecimal totalSpend, String averageCpc, String currency, Integer oneDayOrdersPlaced,
			BigDecimal oneDayOrderedProductSales, String oneDayConversionRate, Integer oneDaySameSkuUnitsOrdered,
			Integer oneDayOtherSkuUnitsOrdered, BigDecimal oneDaySameSkuUnitsOrderedProductSales,
			BigDecimal oneDayOtherSkuUnitsOrderedProductSales, Integer oneWeekOrdersPlaced,
			BigDecimal oneWeekOrderedProductSales, String oneWeekConversionRate, Integer oneWeekSameSkuUnitsOrdered,
			Integer oneWeekOtherSkuUnitsOrdered, BigDecimal oneWeekSameSkuUnitsOrderedProductSales,
			BigDecimal oneWeekOtherSkuUnitsOrderedProductSales, Integer oneMonthOrdersPlaced,
			BigDecimal oneMonthOrderedProductSales, String oneMonthConversionRate, Integer oneMonthSameSkuUnitsOrdered,
			Integer oneMonthOtherSkuUnitsOrdered, BigDecimal oneMonthSameSkuUnitsOrderedProductSales,
			BigDecimal oneMonthOtherSkuUnitsOrderedProductSales) {
		this.store = store;
		this.insertDate = insertDate;
		this.campaignName = campaignName;
		this.adGroupName = adGroupName;
		this.advertisedSku = advertisedSku;
		this.keyword = keyword;
		this.matchType = matchType;
		this.startDate = startDate;
		this.endDate = endDate;
		this.clicks = clicks;
		this.impressions = impressions;
		this.ctr = ctr;
		this.totalSpend = totalSpend;
		this.averageCpc = averageCpc;
		this.currency = currency;
		this.oneDayOrdersPlaced = oneDayOrdersPlaced;
		this.oneDayOrderedProductSales = oneDayOrderedProductSales;
		this.oneDayConversionRate = oneDayConversionRate;
		this.oneDaySameSkuUnitsOrdered = oneDaySameSkuUnitsOrdered;
		this.oneDayOtherSkuUnitsOrdered = oneDayOtherSkuUnitsOrdered;
		this.oneDaySameSkuUnitsOrderedProductSales = oneDaySameSkuUnitsOrderedProductSales;
		this.oneDayOtherSkuUnitsOrderedProductSales = oneDayOtherSkuUnitsOrderedProductSales;
		this.oneWeekOrdersPlaced = oneWeekOrdersPlaced;
		this.oneWeekOrderedProductSales = oneWeekOrderedProductSales;
		this.oneWeekConversionRate = oneWeekConversionRate;
		this.oneWeekSameSkuUnitsOrdered = oneWeekSameSkuUnitsOrdered;
		this.oneWeekOtherSkuUnitsOrdered = oneWeekOtherSkuUnitsOrdered;
		this.oneWeekSameSkuUnitsOrderedProductSales = oneWeekSameSkuUnitsOrderedProductSales;
		this.oneWeekOtherSkuUnitsOrderedProductSales = oneWeekOtherSkuUnitsOrderedProductSales;
		this.oneMonthOrdersPlaced = oneMonthOrdersPlaced;
		this.oneMonthOrderedProductSales = oneMonthOrderedProductSales;
		this.oneMonthConversionRate = oneMonthConversionRate;
		this.oneMonthSameSkuUnitsOrdered = oneMonthSameSkuUnitsOrdered;
		this.oneMonthOtherSkuUnitsOrdered = oneMonthOtherSkuUnitsOrdered;
		this.oneMonthSameSkuUnitsOrderedProductSales = oneMonthSameSkuUnitsOrderedProductSales;
		this.oneMonthOtherSkuUnitsOrderedProductSales = oneMonthOtherSkuUnitsOrderedProductSales;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStore() {
		return this.store;
	}

	public void setStore(String store) {
		this.store = store;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public String getCampaignName() {
		return this.campaignName;
	}

	public void setCampaignName(String campaignName) {
		this.campaignName = campaignName;
	}

	public String getAdGroupName() {
		return this.adGroupName;
	}

	public void setAdGroupName(String adGroupName) {
		this.adGroupName = adGroupName;
	}

	public String getAdvertisedSku() {
		return this.advertisedSku;
	}

	public void setAdvertisedSku(String advertisedSku) {
		this.advertisedSku = advertisedSku;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public String getMatchType() {
		return this.matchType;
	}

	public void setMatchType(String matchType) {
		this.matchType = matchType;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getClicks() {
		return this.clicks;
	}

	public void setClicks(Integer clicks) {
		this.clicks = clicks;
	}

	public Integer getImpressions() {
		return this.impressions;
	}

	public void setImpressions(Integer impressions) {
		this.impressions = impressions;
	}

	public String getCtr() {
		return this.ctr;
	}

	public void setCtr(String ctr) {
		this.ctr = ctr;
	}

	public BigDecimal getTotalSpend() {
		return this.totalSpend;
	}

	public void setTotalSpend(BigDecimal totalSpend) {
		this.totalSpend = totalSpend;
	}

	public String getAverageCpc() {
		return this.averageCpc;
	}

	public void setAverageCpc(String averageCpc) {
		this.averageCpc = averageCpc;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public Integer getOneDayOrdersPlaced() {
		return this.oneDayOrdersPlaced;
	}

	public void setOneDayOrdersPlaced(Integer oneDayOrdersPlaced) {
		this.oneDayOrdersPlaced = oneDayOrdersPlaced;
	}

	public BigDecimal getOneDayOrderedProductSales() {
		return this.oneDayOrderedProductSales;
	}

	public void setOneDayOrderedProductSales(BigDecimal oneDayOrderedProductSales) {
		this.oneDayOrderedProductSales = oneDayOrderedProductSales;
	}

	public String getOneDayConversionRate() {
		return this.oneDayConversionRate;
	}

	public void setOneDayConversionRate(String oneDayConversionRate) {
		this.oneDayConversionRate = oneDayConversionRate;
	}

	public Integer getOneDaySameSkuUnitsOrdered() {
		return this.oneDaySameSkuUnitsOrdered;
	}

	public void setOneDaySameSkuUnitsOrdered(Integer oneDaySameSkuUnitsOrdered) {
		this.oneDaySameSkuUnitsOrdered = oneDaySameSkuUnitsOrdered;
	}

	public Integer getOneDayOtherSkuUnitsOrdered() {
		return this.oneDayOtherSkuUnitsOrdered;
	}

	public void setOneDayOtherSkuUnitsOrdered(Integer oneDayOtherSkuUnitsOrdered) {
		this.oneDayOtherSkuUnitsOrdered = oneDayOtherSkuUnitsOrdered;
	}

	public BigDecimal getOneDaySameSkuUnitsOrderedProductSales() {
		return this.oneDaySameSkuUnitsOrderedProductSales;
	}

	public void setOneDaySameSkuUnitsOrderedProductSales(BigDecimal oneDaySameSkuUnitsOrderedProductSales) {
		this.oneDaySameSkuUnitsOrderedProductSales = oneDaySameSkuUnitsOrderedProductSales;
	}

	public BigDecimal getOneDayOtherSkuUnitsOrderedProductSales() {
		return this.oneDayOtherSkuUnitsOrderedProductSales;
	}

	public void setOneDayOtherSkuUnitsOrderedProductSales(BigDecimal oneDayOtherSkuUnitsOrderedProductSales) {
		this.oneDayOtherSkuUnitsOrderedProductSales = oneDayOtherSkuUnitsOrderedProductSales;
	}

	public Integer getOneWeekOrdersPlaced() {
		return this.oneWeekOrdersPlaced;
	}

	public void setOneWeekOrdersPlaced(Integer oneWeekOrdersPlaced) {
		this.oneWeekOrdersPlaced = oneWeekOrdersPlaced;
	}

	public BigDecimal getOneWeekOrderedProductSales() {
		return this.oneWeekOrderedProductSales;
	}

	public void setOneWeekOrderedProductSales(BigDecimal oneWeekOrderedProductSales) {
		this.oneWeekOrderedProductSales = oneWeekOrderedProductSales;
	}

	public String getOneWeekConversionRate() {
		return this.oneWeekConversionRate;
	}

	public void setOneWeekConversionRate(String oneWeekConversionRate) {
		this.oneWeekConversionRate = oneWeekConversionRate;
	}

	public Integer getOneWeekSameSkuUnitsOrdered() {
		return this.oneWeekSameSkuUnitsOrdered;
	}

	public void setOneWeekSameSkuUnitsOrdered(Integer oneWeekSameSkuUnitsOrdered) {
		this.oneWeekSameSkuUnitsOrdered = oneWeekSameSkuUnitsOrdered;
	}

	public Integer getOneWeekOtherSkuUnitsOrdered() {
		return this.oneWeekOtherSkuUnitsOrdered;
	}

	public void setOneWeekOtherSkuUnitsOrdered(Integer oneWeekOtherSkuUnitsOrdered) {
		this.oneWeekOtherSkuUnitsOrdered = oneWeekOtherSkuUnitsOrdered;
	}

	public BigDecimal getOneWeekSameSkuUnitsOrderedProductSales() {
		return this.oneWeekSameSkuUnitsOrderedProductSales;
	}

	public void setOneWeekSameSkuUnitsOrderedProductSales(BigDecimal oneWeekSameSkuUnitsOrderedProductSales) {
		this.oneWeekSameSkuUnitsOrderedProductSales = oneWeekSameSkuUnitsOrderedProductSales;
	}

	public BigDecimal getOneWeekOtherSkuUnitsOrderedProductSales() {
		return this.oneWeekOtherSkuUnitsOrderedProductSales;
	}

	public void setOneWeekOtherSkuUnitsOrderedProductSales(BigDecimal oneWeekOtherSkuUnitsOrderedProductSales) {
		this.oneWeekOtherSkuUnitsOrderedProductSales = oneWeekOtherSkuUnitsOrderedProductSales;
	}

	public Integer getOneMonthOrdersPlaced() {
		return this.oneMonthOrdersPlaced;
	}

	public void setOneMonthOrdersPlaced(Integer oneMonthOrdersPlaced) {
		this.oneMonthOrdersPlaced = oneMonthOrdersPlaced;
	}

	public BigDecimal getOneMonthOrderedProductSales() {
		return this.oneMonthOrderedProductSales;
	}

	public void setOneMonthOrderedProductSales(BigDecimal oneMonthOrderedProductSales) {
		this.oneMonthOrderedProductSales = oneMonthOrderedProductSales;
	}

	public String getOneMonthConversionRate() {
		return this.oneMonthConversionRate;
	}

	public void setOneMonthConversionRate(String oneMonthConversionRate) {
		this.oneMonthConversionRate = oneMonthConversionRate;
	}

	public Integer getOneMonthSameSkuUnitsOrdered() {
		return this.oneMonthSameSkuUnitsOrdered;
	}

	public void setOneMonthSameSkuUnitsOrdered(Integer oneMonthSameSkuUnitsOrdered) {
		this.oneMonthSameSkuUnitsOrdered = oneMonthSameSkuUnitsOrdered;
	}

	public Integer getOneMonthOtherSkuUnitsOrdered() {
		return this.oneMonthOtherSkuUnitsOrdered;
	}

	public void setOneMonthOtherSkuUnitsOrdered(Integer oneMonthOtherSkuUnitsOrdered) {
		this.oneMonthOtherSkuUnitsOrdered = oneMonthOtherSkuUnitsOrdered;
	}

	public BigDecimal getOneMonthSameSkuUnitsOrderedProductSales() {
		return this.oneMonthSameSkuUnitsOrderedProductSales;
	}

	public void setOneMonthSameSkuUnitsOrderedProductSales(BigDecimal oneMonthSameSkuUnitsOrderedProductSales) {
		this.oneMonthSameSkuUnitsOrderedProductSales = oneMonthSameSkuUnitsOrderedProductSales;
	}

	public BigDecimal getOneMonthOtherSkuUnitsOrderedProductSales() {
		return this.oneMonthOtherSkuUnitsOrderedProductSales;
	}

	public void setOneMonthOtherSkuUnitsOrderedProductSales(BigDecimal oneMonthOtherSkuUnitsOrderedProductSales) {
		this.oneMonthOtherSkuUnitsOrderedProductSales = oneMonthOtherSkuUnitsOrderedProductSales;
	}

}
