package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * ReportInventory generated by hbm2java
 */
public class ReportInventory implements java.io.Serializable {

	private Integer id;
	private String store;
	private Date insertDate;
	private String sku;
	private String asin;
	private BigDecimal price;
	private Integer quantity;

	public ReportInventory() {
	}

	public ReportInventory(String store, Date insertDate, String sku, String asin, BigDecimal price, Integer quantity) {
		this.store = store;
		this.insertDate = insertDate;
		this.sku = sku;
		this.asin = asin;
		this.price = price;
		this.quantity = quantity;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStore() {
		return this.store;
	}

	public void setStore(String store) {
		this.store = store;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	public String getAsin() {
		return this.asin;
	}

	public void setAsin(String asin) {
		this.asin = asin;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
