package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ReportFbaAmazonFulfilledInventory generated by hbm2java
 */
public class ReportFbaAmazonFulfilledInventory implements java.io.Serializable {

	private Integer id;
	private String store;
	private Date insertDate;
	private String sellerSku;
	private String fulfillmentChannelSku;
	private String asin;
	private String conditionType;
	private String warehouseConditionCode;
	private Integer quantityAvailable;

	public ReportFbaAmazonFulfilledInventory() {
	}

	public ReportFbaAmazonFulfilledInventory(String store, Date insertDate, String sellerSku,
			String fulfillmentChannelSku, String asin, String conditionType, String warehouseConditionCode,
			Integer quantityAvailable) {
		this.store = store;
		this.insertDate = insertDate;
		this.sellerSku = sellerSku;
		this.fulfillmentChannelSku = fulfillmentChannelSku;
		this.asin = asin;
		this.conditionType = conditionType;
		this.warehouseConditionCode = warehouseConditionCode;
		this.quantityAvailable = quantityAvailable;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStore() {
		return this.store;
	}

	public void setStore(String store) {
		this.store = store;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public String getSellerSku() {
		return this.sellerSku;
	}

	public void setSellerSku(String sellerSku) {
		this.sellerSku = sellerSku;
	}

	public String getFulfillmentChannelSku() {
		return this.fulfillmentChannelSku;
	}

	public void setFulfillmentChannelSku(String fulfillmentChannelSku) {
		this.fulfillmentChannelSku = fulfillmentChannelSku;
	}

	public String getAsin() {
		return this.asin;
	}

	public void setAsin(String asin) {
		this.asin = asin;
	}

	public String getConditionType() {
		return this.conditionType;
	}

	public void setConditionType(String conditionType) {
		this.conditionType = conditionType;
	}

	public String getWarehouseConditionCode() {
		return this.warehouseConditionCode;
	}

	public void setWarehouseConditionCode(String warehouseConditionCode) {
		this.warehouseConditionCode = warehouseConditionCode;
	}

	public Integer getQuantityAvailable() {
		return this.quantityAvailable;
	}

	public void setQuantityAvailable(Integer quantityAvailable) {
		this.quantityAvailable = quantityAvailable;
	}

}
