package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * ReportFbaAmazonFulfilledShipments generated by hbm2java
 */
public class ReportFbaAmazonFulfilledShipments implements java.io.Serializable {

	private ReportFbaAmazonFulfilledShipmentsId id;
	private String store;
	private Date insertDate;
	private String merchantOrderId;
	private String amazonOrderItemId;
	private String merchantOrderItemId;
	private Date purchaseDate;
	private Date paymentsDate;
	private Date shipmentDate;
	private Date reportingDate;
	private String buyerEmail;
	private String buyerName;
	private String buyerPhoneNumber;
	private String sku;
	private String productName;
	private Integer quantityShipped;
	private String currency;
	private BigDecimal itemPrice;
	private BigDecimal itemTax;
	private BigDecimal shippingPrice;
	private BigDecimal shippingTax;
	private BigDecimal giftWrapPrice;
	private BigDecimal giftWrapTax;
	private String shipServiceLevel;
	private String recipientName;
	private String shipAddress1;
	private String shipAddress2;
	private String shipAddress3;
	private String shipCity;
	private String shipState;
	private String shipPostalCode;
	private String shipCountry;
	private BigDecimal itemPromotionDiscount;
	private BigDecimal shipPromotionDiscount;
	private String carrier;
	private String trackingNumber;
	private Date estimatedArrivalDate;
	private String fulfillmentCenterId;
	private String fulfillmentChannel;
	private String salesChannel;

	public ReportFbaAmazonFulfilledShipments() {
	}

	public ReportFbaAmazonFulfilledShipments(ReportFbaAmazonFulfilledShipmentsId id) {
		this.id = id;
	}

	public ReportFbaAmazonFulfilledShipments(ReportFbaAmazonFulfilledShipmentsId id, String store, Date insertDate,
			String merchantOrderId, String amazonOrderItemId, String merchantOrderItemId, Date purchaseDate,
			Date paymentsDate, Date shipmentDate, Date reportingDate, String buyerEmail, String buyerName,
			String buyerPhoneNumber, String sku, String productName, Integer quantityShipped, String currency,
			BigDecimal itemPrice, BigDecimal itemTax, BigDecimal shippingPrice, BigDecimal shippingTax,
			BigDecimal giftWrapPrice, BigDecimal giftWrapTax, String shipServiceLevel, String recipientName,
			String shipAddress1, String shipAddress2, String shipAddress3, String shipCity, String shipState,
			String shipPostalCode, String shipCountry, BigDecimal itemPromotionDiscount,
			BigDecimal shipPromotionDiscount, String carrier, String trackingNumber, Date estimatedArrivalDate,
			String fulfillmentCenterId, String fulfillmentChannel, String salesChannel) {
		this.id = id;
		this.store = store;
		this.insertDate = insertDate;
		this.merchantOrderId = merchantOrderId;
		this.amazonOrderItemId = amazonOrderItemId;
		this.merchantOrderItemId = merchantOrderItemId;
		this.purchaseDate = purchaseDate;
		this.paymentsDate = paymentsDate;
		this.shipmentDate = shipmentDate;
		this.reportingDate = reportingDate;
		this.buyerEmail = buyerEmail;
		this.buyerName = buyerName;
		this.buyerPhoneNumber = buyerPhoneNumber;
		this.sku = sku;
		this.productName = productName;
		this.quantityShipped = quantityShipped;
		this.currency = currency;
		this.itemPrice = itemPrice;
		this.itemTax = itemTax;
		this.shippingPrice = shippingPrice;
		this.shippingTax = shippingTax;
		this.giftWrapPrice = giftWrapPrice;
		this.giftWrapTax = giftWrapTax;
		this.shipServiceLevel = shipServiceLevel;
		this.recipientName = recipientName;
		this.shipAddress1 = shipAddress1;
		this.shipAddress2 = shipAddress2;
		this.shipAddress3 = shipAddress3;
		this.shipCity = shipCity;
		this.shipState = shipState;
		this.shipPostalCode = shipPostalCode;
		this.shipCountry = shipCountry;
		this.itemPromotionDiscount = itemPromotionDiscount;
		this.shipPromotionDiscount = shipPromotionDiscount;
		this.carrier = carrier;
		this.trackingNumber = trackingNumber;
		this.estimatedArrivalDate = estimatedArrivalDate;
		this.fulfillmentCenterId = fulfillmentCenterId;
		this.fulfillmentChannel = fulfillmentChannel;
		this.salesChannel = salesChannel;
	}

	public ReportFbaAmazonFulfilledShipmentsId getId() {
		return this.id;
	}

	public void setId(ReportFbaAmazonFulfilledShipmentsId id) {
		this.id = id;
	}

	public String getStore() {
		return this.store;
	}

	public void setStore(String store) {
		this.store = store;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public String getMerchantOrderId() {
		return this.merchantOrderId;
	}

	public void setMerchantOrderId(String merchantOrderId) {
		this.merchantOrderId = merchantOrderId;
	}

	public String getAmazonOrderItemId() {
		return this.amazonOrderItemId;
	}

	public void setAmazonOrderItemId(String amazonOrderItemId) {
		this.amazonOrderItemId = amazonOrderItemId;
	}

	public String getMerchantOrderItemId() {
		return this.merchantOrderItemId;
	}

	public void setMerchantOrderItemId(String merchantOrderItemId) {
		this.merchantOrderItemId = merchantOrderItemId;
	}

	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	public Date getPaymentsDate() {
		return this.paymentsDate;
	}

	public void setPaymentsDate(Date paymentsDate) {
		this.paymentsDate = paymentsDate;
	}

	public Date getShipmentDate() {
		return this.shipmentDate;
	}

	public void setShipmentDate(Date shipmentDate) {
		this.shipmentDate = shipmentDate;
	}

	public Date getReportingDate() {
		return this.reportingDate;
	}

	public void setReportingDate(Date reportingDate) {
		this.reportingDate = reportingDate;
	}

	public String getBuyerEmail() {
		return this.buyerEmail;
	}

	public void setBuyerEmail(String buyerEmail) {
		this.buyerEmail = buyerEmail;
	}

	public String getBuyerName() {
		return this.buyerName;
	}

	public void setBuyerName(String buyerName) {
		this.buyerName = buyerName;
	}

	public String getBuyerPhoneNumber() {
		return this.buyerPhoneNumber;
	}

	public void setBuyerPhoneNumber(String buyerPhoneNumber) {
		this.buyerPhoneNumber = buyerPhoneNumber;
	}

	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public Integer getQuantityShipped() {
		return this.quantityShipped;
	}

	public void setQuantityShipped(Integer quantityShipped) {
		this.quantityShipped = quantityShipped;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public BigDecimal getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(BigDecimal itemPrice) {
		this.itemPrice = itemPrice;
	}

	public BigDecimal getItemTax() {
		return this.itemTax;
	}

	public void setItemTax(BigDecimal itemTax) {
		this.itemTax = itemTax;
	}

	public BigDecimal getShippingPrice() {
		return this.shippingPrice;
	}

	public void setShippingPrice(BigDecimal shippingPrice) {
		this.shippingPrice = shippingPrice;
	}

	public BigDecimal getShippingTax() {
		return this.shippingTax;
	}

	public void setShippingTax(BigDecimal shippingTax) {
		this.shippingTax = shippingTax;
	}

	public BigDecimal getGiftWrapPrice() {
		return this.giftWrapPrice;
	}

	public void setGiftWrapPrice(BigDecimal giftWrapPrice) {
		this.giftWrapPrice = giftWrapPrice;
	}

	public BigDecimal getGiftWrapTax() {
		return this.giftWrapTax;
	}

	public void setGiftWrapTax(BigDecimal giftWrapTax) {
		this.giftWrapTax = giftWrapTax;
	}

	public String getShipServiceLevel() {
		return this.shipServiceLevel;
	}

	public void setShipServiceLevel(String shipServiceLevel) {
		this.shipServiceLevel = shipServiceLevel;
	}

	public String getRecipientName() {
		return this.recipientName;
	}

	public void setRecipientName(String recipientName) {
		this.recipientName = recipientName;
	}

	public String getShipAddress1() {
		return this.shipAddress1;
	}

	public void setShipAddress1(String shipAddress1) {
		this.shipAddress1 = shipAddress1;
	}

	public String getShipAddress2() {
		return this.shipAddress2;
	}

	public void setShipAddress2(String shipAddress2) {
		this.shipAddress2 = shipAddress2;
	}

	public String getShipAddress3() {
		return this.shipAddress3;
	}

	public void setShipAddress3(String shipAddress3) {
		this.shipAddress3 = shipAddress3;
	}

	public String getShipCity() {
		return this.shipCity;
	}

	public void setShipCity(String shipCity) {
		this.shipCity = shipCity;
	}

	public String getShipState() {
		return this.shipState;
	}

	public void setShipState(String shipState) {
		this.shipState = shipState;
	}

	public String getShipPostalCode() {
		return this.shipPostalCode;
	}

	public void setShipPostalCode(String shipPostalCode) {
		this.shipPostalCode = shipPostalCode;
	}

	public String getShipCountry() {
		return this.shipCountry;
	}

	public void setShipCountry(String shipCountry) {
		this.shipCountry = shipCountry;
	}

	public BigDecimal getItemPromotionDiscount() {
		return this.itemPromotionDiscount;
	}

	public void setItemPromotionDiscount(BigDecimal itemPromotionDiscount) {
		this.itemPromotionDiscount = itemPromotionDiscount;
	}

	public BigDecimal getShipPromotionDiscount() {
		return this.shipPromotionDiscount;
	}

	public void setShipPromotionDiscount(BigDecimal shipPromotionDiscount) {
		this.shipPromotionDiscount = shipPromotionDiscount;
	}

	public String getCarrier() {
		return this.carrier;
	}

	public void setCarrier(String carrier) {
		this.carrier = carrier;
	}

	public String getTrackingNumber() {
		return this.trackingNumber;
	}

	public void setTrackingNumber(String trackingNumber) {
		this.trackingNumber = trackingNumber;
	}

	public Date getEstimatedArrivalDate() {
		return this.estimatedArrivalDate;
	}

	public void setEstimatedArrivalDate(Date estimatedArrivalDate) {
		this.estimatedArrivalDate = estimatedArrivalDate;
	}

	public String getFulfillmentCenterId() {
		return this.fulfillmentCenterId;
	}

	public void setFulfillmentCenterId(String fulfillmentCenterId) {
		this.fulfillmentCenterId = fulfillmentCenterId;
	}

	public String getFulfillmentChannel() {
		return this.fulfillmentChannel;
	}

	public void setFulfillmentChannel(String fulfillmentChannel) {
		this.fulfillmentChannel = fulfillmentChannel;
	}

	public String getSalesChannel() {
		return this.salesChannel;
	}

	public void setSalesChannel(String salesChannel) {
		this.salesChannel = salesChannel;
	}

}
