package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

/**
 * ReportScheduledReportType generated by hbm2java
 */
public class ReportScheduledReportType implements java.io.Serializable {

	private Integer id;
	private String reportType;
	private Integer enabled;

	public ReportScheduledReportType() {
	}

	public ReportScheduledReportType(String reportType, Integer enabled) {
		this.reportType = reportType;
		this.enabled = enabled;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getReportType() {
		return this.reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	public Integer getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Integer enabled) {
		this.enabled = enabled;
	}

}
