package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ReportUnshippedOrders generated by hbm2java
 */
public class ReportUnshippedOrders implements java.io.Serializable {

	private Integer id;
	private String store;
	private Date insertDate;
	private String orderId;
	private String orderItemId;
	private Date purchaseDate;
	private Date paymentsDate;
	private Date reportingDate;
	private Date promiseDate;
	private Integer daysPastPromise;
	private String buyerEmail;
	private String buyerName;
	private String buyerPhoneNumber;
	private String sku;
	private String productName;
	private Integer quantityPurchased;
	private Integer quantityShipped;
	private Integer quantityToShip;
	private String shipServiceLevel;
	private String recipientName;
	private String shipAddress1;
	private String shipAddress2;
	private String shipAddress3;
	private String shipCity;
	private String shipState;
	private String shipPostalCode;
	private String shipCountry;
	private String isBusinessOrder;
	private String purchaseOrderNumber;
	private String priceDesignation;

	public ReportUnshippedOrders() {
	}

	public ReportUnshippedOrders(String store, Date insertDate, String orderId, String orderItemId, Date purchaseDate,
			Date paymentsDate, Date reportingDate, Date promiseDate, Integer daysPastPromise, String buyerEmail,
			String buyerName, String buyerPhoneNumber, String sku, String productName, Integer quantityPurchased,
			Integer quantityShipped, Integer quantityToShip, String shipServiceLevel, String recipientName,
			String shipAddress1, String shipAddress2, String shipAddress3, String shipCity, String shipState,
			String shipPostalCode, String shipCountry, String isBusinessOrder, String purchaseOrderNumber,
			String priceDesignation) {
		this.store = store;
		this.insertDate = insertDate;
		this.orderId = orderId;
		this.orderItemId = orderItemId;
		this.purchaseDate = purchaseDate;
		this.paymentsDate = paymentsDate;
		this.reportingDate = reportingDate;
		this.promiseDate = promiseDate;
		this.daysPastPromise = daysPastPromise;
		this.buyerEmail = buyerEmail;
		this.buyerName = buyerName;
		this.buyerPhoneNumber = buyerPhoneNumber;
		this.sku = sku;
		this.productName = productName;
		this.quantityPurchased = quantityPurchased;
		this.quantityShipped = quantityShipped;
		this.quantityToShip = quantityToShip;
		this.shipServiceLevel = shipServiceLevel;
		this.recipientName = recipientName;
		this.shipAddress1 = shipAddress1;
		this.shipAddress2 = shipAddress2;
		this.shipAddress3 = shipAddress3;
		this.shipCity = shipCity;
		this.shipState = shipState;
		this.shipPostalCode = shipPostalCode;
		this.shipCountry = shipCountry;
		this.isBusinessOrder = isBusinessOrder;
		this.purchaseOrderNumber = purchaseOrderNumber;
		this.priceDesignation = priceDesignation;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStore() {
		return this.store;
	}

	public void setStore(String store) {
		this.store = store;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(String orderItemId) {
		this.orderItemId = orderItemId;
	}

	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	public Date getPaymentsDate() {
		return this.paymentsDate;
	}

	public void setPaymentsDate(Date paymentsDate) {
		this.paymentsDate = paymentsDate;
	}

	public Date getReportingDate() {
		return this.reportingDate;
	}

	public void setReportingDate(Date reportingDate) {
		this.reportingDate = reportingDate;
	}

	public Date getPromiseDate() {
		return this.promiseDate;
	}

	public void setPromiseDate(Date promiseDate) {
		this.promiseDate = promiseDate;
	}

	public Integer getDaysPastPromise() {
		return this.daysPastPromise;
	}

	public void setDaysPastPromise(Integer daysPastPromise) {
		this.daysPastPromise = daysPastPromise;
	}

	public String getBuyerEmail() {
		return this.buyerEmail;
	}

	public void setBuyerEmail(String buyerEmail) {
		this.buyerEmail = buyerEmail;
	}

	public String getBuyerName() {
		return this.buyerName;
	}

	public void setBuyerName(String buyerName) {
		this.buyerName = buyerName;
	}

	public String getBuyerPhoneNumber() {
		return this.buyerPhoneNumber;
	}

	public void setBuyerPhoneNumber(String buyerPhoneNumber) {
		this.buyerPhoneNumber = buyerPhoneNumber;
	}

	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public Integer getQuantityPurchased() {
		return this.quantityPurchased;
	}

	public void setQuantityPurchased(Integer quantityPurchased) {
		this.quantityPurchased = quantityPurchased;
	}

	public Integer getQuantityShipped() {
		return this.quantityShipped;
	}

	public void setQuantityShipped(Integer quantityShipped) {
		this.quantityShipped = quantityShipped;
	}

	public Integer getQuantityToShip() {
		return this.quantityToShip;
	}

	public void setQuantityToShip(Integer quantityToShip) {
		this.quantityToShip = quantityToShip;
	}

	public String getShipServiceLevel() {
		return this.shipServiceLevel;
	}

	public void setShipServiceLevel(String shipServiceLevel) {
		this.shipServiceLevel = shipServiceLevel;
	}

	public String getRecipientName() {
		return this.recipientName;
	}

	public void setRecipientName(String recipientName) {
		this.recipientName = recipientName;
	}

	public String getShipAddress1() {
		return this.shipAddress1;
	}

	public void setShipAddress1(String shipAddress1) {
		this.shipAddress1 = shipAddress1;
	}

	public String getShipAddress2() {
		return this.shipAddress2;
	}

	public void setShipAddress2(String shipAddress2) {
		this.shipAddress2 = shipAddress2;
	}

	public String getShipAddress3() {
		return this.shipAddress3;
	}

	public void setShipAddress3(String shipAddress3) {
		this.shipAddress3 = shipAddress3;
	}

	public String getShipCity() {
		return this.shipCity;
	}

	public void setShipCity(String shipCity) {
		this.shipCity = shipCity;
	}

	public String getShipState() {
		return this.shipState;
	}

	public void setShipState(String shipState) {
		this.shipState = shipState;
	}

	public String getShipPostalCode() {
		return this.shipPostalCode;
	}

	public void setShipPostalCode(String shipPostalCode) {
		this.shipPostalCode = shipPostalCode;
	}

	public String getShipCountry() {
		return this.shipCountry;
	}

	public void setShipCountry(String shipCountry) {
		this.shipCountry = shipCountry;
	}

	public String getIsBusinessOrder() {
		return this.isBusinessOrder;
	}

	public void setIsBusinessOrder(String isBusinessOrder) {
		this.isBusinessOrder = isBusinessOrder;
	}

	public String getPurchaseOrderNumber() {
		return this.purchaseOrderNumber;
	}

	public void setPurchaseOrderNumber(String purchaseOrderNumber) {
		this.purchaseOrderNumber = purchaseOrderNumber;
	}

	public String getPriceDesignation() {
		return this.priceDesignation;
	}

	public void setPriceDesignation(String priceDesignation) {
		this.priceDesignation = priceDesignation;
	}

}
