package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * ReportAdsAutoTargeting generated by hbm2java
 */
public class ReportAdsAutoTargeting implements java.io.Serializable {

	private Integer id;
	private String store;
	private Date insertDate;
	private String campaign;
	private String adGroupName;
	private String customerSearchTerm;
	private String keyword;
	private String matchType;
	private Date firstDayOfImpression;
	private Date lastDayOfImpression;
	private Integer impressions;
	private Integer clicks;
	private String ctr;
	private BigDecimal totalSpend;
	private Float averageCpc;
	private String acos;
	private String currency;
	private Integer orderPlacedWithin1WeekOfAClick;
	private BigDecimal productSalesWithin1WeekOfAClick;
	private String convertionRateWithin1WeekOfAClick;
	private Integer sameSkuUnitsOrderedWithin1WeekOfClick;
	private Integer otherSkuUnitsOrderedWithin1WeekOfClick;
	private BigDecimal sameSkuUnitsProductSalesWithin1WeekOfClick;
	private BigDecimal otherSkuUnitsProductSalesWithin1WeekOfClick;

	public ReportAdsAutoTargeting() {
	}

	public ReportAdsAutoTargeting(String store, Date insertDate, String campaign, String adGroupName,
			String customerSearchTerm, String keyword, String matchType, Date firstDayOfImpression,
			Date lastDayOfImpression, Integer impressions, Integer clicks, String ctr, BigDecimal totalSpend,
			Float averageCpc, String acos, String currency, Integer orderPlacedWithin1WeekOfAClick,
			BigDecimal productSalesWithin1WeekOfAClick, String convertionRateWithin1WeekOfAClick,
			Integer sameSkuUnitsOrderedWithin1WeekOfClick, Integer otherSkuUnitsOrderedWithin1WeekOfClick,
			BigDecimal sameSkuUnitsProductSalesWithin1WeekOfClick,
			BigDecimal otherSkuUnitsProductSalesWithin1WeekOfClick) {
		this.store = store;
		this.insertDate = insertDate;
		this.campaign = campaign;
		this.adGroupName = adGroupName;
		this.customerSearchTerm = customerSearchTerm;
		this.keyword = keyword;
		this.matchType = matchType;
		this.firstDayOfImpression = firstDayOfImpression;
		this.lastDayOfImpression = lastDayOfImpression;
		this.impressions = impressions;
		this.clicks = clicks;
		this.ctr = ctr;
		this.totalSpend = totalSpend;
		this.averageCpc = averageCpc;
		this.acos = acos;
		this.currency = currency;
		this.orderPlacedWithin1WeekOfAClick = orderPlacedWithin1WeekOfAClick;
		this.productSalesWithin1WeekOfAClick = productSalesWithin1WeekOfAClick;
		this.convertionRateWithin1WeekOfAClick = convertionRateWithin1WeekOfAClick;
		this.sameSkuUnitsOrderedWithin1WeekOfClick = sameSkuUnitsOrderedWithin1WeekOfClick;
		this.otherSkuUnitsOrderedWithin1WeekOfClick = otherSkuUnitsOrderedWithin1WeekOfClick;
		this.sameSkuUnitsProductSalesWithin1WeekOfClick = sameSkuUnitsProductSalesWithin1WeekOfClick;
		this.otherSkuUnitsProductSalesWithin1WeekOfClick = otherSkuUnitsProductSalesWithin1WeekOfClick;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStore() {
		return this.store;
	}

	public void setStore(String store) {
		this.store = store;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public String getCampaign() {
		return this.campaign;
	}

	public void setCampaign(String campaign) {
		this.campaign = campaign;
	}

	public String getAdGroupName() {
		return this.adGroupName;
	}

	public void setAdGroupName(String adGroupName) {
		this.adGroupName = adGroupName;
	}

	public String getCustomerSearchTerm() {
		return this.customerSearchTerm;
	}

	public void setCustomerSearchTerm(String customerSearchTerm) {
		this.customerSearchTerm = customerSearchTerm;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public String getMatchType() {
		return this.matchType;
	}

	public void setMatchType(String matchType) {
		this.matchType = matchType;
	}

	public Date getFirstDayOfImpression() {
		return this.firstDayOfImpression;
	}

	public void setFirstDayOfImpression(Date firstDayOfImpression) {
		this.firstDayOfImpression = firstDayOfImpression;
	}

	public Date getLastDayOfImpression() {
		return this.lastDayOfImpression;
	}

	public void setLastDayOfImpression(Date lastDayOfImpression) {
		this.lastDayOfImpression = lastDayOfImpression;
	}

	public Integer getImpressions() {
		return this.impressions;
	}

	public void setImpressions(Integer impressions) {
		this.impressions = impressions;
	}

	public Integer getClicks() {
		return this.clicks;
	}

	public void setClicks(Integer clicks) {
		this.clicks = clicks;
	}

	public String getCtr() {
		return this.ctr;
	}

	public void setCtr(String ctr) {
		this.ctr = ctr;
	}

	public BigDecimal getTotalSpend() {
		return this.totalSpend;
	}

	public void setTotalSpend(BigDecimal totalSpend) {
		this.totalSpend = totalSpend;
	}

	public Float getAverageCpc() {
		return this.averageCpc;
	}

	public void setAverageCpc(Float averageCpc) {
		this.averageCpc = averageCpc;
	}

	public String getAcos() {
		return this.acos;
	}

	public void setAcos(String acos) {
		this.acos = acos;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public Integer getOrderPlacedWithin1WeekOfAClick() {
		return this.orderPlacedWithin1WeekOfAClick;
	}

	public void setOrderPlacedWithin1WeekOfAClick(Integer orderPlacedWithin1WeekOfAClick) {
		this.orderPlacedWithin1WeekOfAClick = orderPlacedWithin1WeekOfAClick;
	}

	public BigDecimal getProductSalesWithin1WeekOfAClick() {
		return this.productSalesWithin1WeekOfAClick;
	}

	public void setProductSalesWithin1WeekOfAClick(BigDecimal productSalesWithin1WeekOfAClick) {
		this.productSalesWithin1WeekOfAClick = productSalesWithin1WeekOfAClick;
	}

	public String getConvertionRateWithin1WeekOfAClick() {
		return this.convertionRateWithin1WeekOfAClick;
	}

	public void setConvertionRateWithin1WeekOfAClick(String convertionRateWithin1WeekOfAClick) {
		this.convertionRateWithin1WeekOfAClick = convertionRateWithin1WeekOfAClick;
	}

	public Integer getSameSkuUnitsOrderedWithin1WeekOfClick() {
		return this.sameSkuUnitsOrderedWithin1WeekOfClick;
	}

	public void setSameSkuUnitsOrderedWithin1WeekOfClick(Integer sameSkuUnitsOrderedWithin1WeekOfClick) {
		this.sameSkuUnitsOrderedWithin1WeekOfClick = sameSkuUnitsOrderedWithin1WeekOfClick;
	}

	public Integer getOtherSkuUnitsOrderedWithin1WeekOfClick() {
		return this.otherSkuUnitsOrderedWithin1WeekOfClick;
	}

	public void setOtherSkuUnitsOrderedWithin1WeekOfClick(Integer otherSkuUnitsOrderedWithin1WeekOfClick) {
		this.otherSkuUnitsOrderedWithin1WeekOfClick = otherSkuUnitsOrderedWithin1WeekOfClick;
	}

	public BigDecimal getSameSkuUnitsProductSalesWithin1WeekOfClick() {
		return this.sameSkuUnitsProductSalesWithin1WeekOfClick;
	}

	public void setSameSkuUnitsProductSalesWithin1WeekOfClick(BigDecimal sameSkuUnitsProductSalesWithin1WeekOfClick) {
		this.sameSkuUnitsProductSalesWithin1WeekOfClick = sameSkuUnitsProductSalesWithin1WeekOfClick;
	}

	public BigDecimal getOtherSkuUnitsProductSalesWithin1WeekOfClick() {
		return this.otherSkuUnitsProductSalesWithin1WeekOfClick;
	}

	public void setOtherSkuUnitsProductSalesWithin1WeekOfClick(BigDecimal otherSkuUnitsProductSalesWithin1WeekOfClick) {
		this.otherSkuUnitsProductSalesWithin1WeekOfClick = otherSkuUnitsProductSalesWithin1WeekOfClick;
	}

}
