package dao.entities;
// Generated 2016-8-8 16:52:31 by Hibernate Tools 4.3.1.Final

/**
 * ReportFbaAmazonFulfilledShipmentsId generated by hbm2java
 */
public class ReportFbaAmazonFulfilledShipmentsId implements java.io.Serializable {

	private String amazonOrderId;
	private String shipmentId;
	private String shipmentItemId;

	public ReportFbaAmazonFulfilledShipmentsId() {
	}

	public ReportFbaAmazonFulfilledShipmentsId(String amazonOrderId, String shipmentId, String shipmentItemId) {
		this.amazonOrderId = amazonOrderId;
		this.shipmentId = shipmentId;
		this.shipmentItemId = shipmentItemId;
	}

	public String getAmazonOrderId() {
		return this.amazonOrderId;
	}

	public void setAmazonOrderId(String amazonOrderId) {
		this.amazonOrderId = amazonOrderId;
	}

	public String getShipmentId() {
		return this.shipmentId;
	}

	public void setShipmentId(String shipmentId) {
		this.shipmentId = shipmentId;
	}

	public String getShipmentItemId() {
		return this.shipmentItemId;
	}

	public void setShipmentItemId(String shipmentItemId) {
		this.shipmentItemId = shipmentItemId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReportFbaAmazonFulfilledShipmentsId))
			return false;
		ReportFbaAmazonFulfilledShipmentsId castOther = (ReportFbaAmazonFulfilledShipmentsId) other;

		return ((this.getAmazonOrderId() == castOther.getAmazonOrderId())
				|| (this.getAmazonOrderId() != null && castOther.getAmazonOrderId() != null
						&& this.getAmazonOrderId().equals(castOther.getAmazonOrderId())))
				&& ((this.getShipmentId() == castOther.getShipmentId()) || (this.getShipmentId() != null
						&& castOther.getShipmentId() != null && this.getShipmentId().equals(castOther.getShipmentId())))
				&& ((this.getShipmentItemId() == castOther.getShipmentItemId())
						|| (this.getShipmentItemId() != null && castOther.getShipmentItemId() != null
								&& this.getShipmentItemId().equals(castOther.getShipmentItemId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAmazonOrderId() == null ? 0 : this.getAmazonOrderId().hashCode());
		result = 37 * result + (getShipmentId() == null ? 0 : this.getShipmentId().hashCode());
		result = 37 * result + (getShipmentItemId() == null ? 0 : this.getShipmentItemId().hashCode());
		return result;
	}

}
